### ISSUE TITLE
open ./components/secrets.json: no such file or directory

### ISSUE THREAD

**Issue by spatxos** [dapr/dotnet-sdk#1106]
## Expected Behavior

dapr's sidecar and Identity.API services should start correctly

## Actual Behavior
The sidecar did not start correctly because it did not find `secrets.json` , which may be the reason for `builder.Configuration.AddDaprSecretStore("secretstore", new DaprClientBuilder().Build()); `error
```
WARN[0000] A non-YAML Component file eshop-secrets.json was detected, it will not be loaded  instance=worker1 scope=dapr.runtime.components type=log ver=unknown
ℹ️  Starting Dapr with id Identity-API. HTTP Port: 3500. gRPC Port: 50001
INFO[0000] starting Dapr Runtime -- version 1.10.7 -- commit f551d4030d5a4333815a0474ca6af6739329027c  app_id=Identity-API instance=worker1 scope=dapr.runtime type=log ver=1.10.7
INFO[0000] log level set to: info                        app_id=Identity-API instance=worker1 scope=dapr.runtime type=log ver=1.10.7
INFO[0000] metrics server started on :43339/             app_id=Identity-API instance=worker1 scope=dapr.metrics type=log ver=1.10.7
WARN[0000] A non-YAML resiliency file eshop-secrets.json was detected, it will not be loaded  app_id=Identity-API instance=worker1 scope=dapr.runtime type=log ver=1.10.7
INFO[0000] Resiliency configuration loaded.              app_id=Identity-API instance=worker1 scope=dapr.runtime type=log ver=1.10.7
INFO[0000] standalone mode configured                    app_id=Identity-API instance=worker1 scope=dapr.runtime type=log ver=1.10.7
INFO[0000] app id: Identity-API                          app_id=Identity-API instance=worker1 scope=dapr.runtime type=log ver=1.10.7
INFO[0000] mTLS is disabled. Skipping certificate request and tls validation  app_id=Identity-API instance=worker1 scope=dapr.runtime type=log ver=1.10.7
INFO[0000] Dapr trace sampler initialized: DaprTraceSampler(P=1.000000)  app_id=Identity-API instance=worker1 scope=dapr.runtime type=log ver=1.10.7
INFO[0000] local service entry announced: Identity-API -> 192.168.110.170:46287  app_id=Identity-API component="mdns (nameResolution/v1)" instance=worker1 scope=dapr.contrib type=log ver=1.10.7
INFO[0000] Initialized name resolution to mdns           app_id=Identity-API instance=worker1 scope=dapr.runtime type=log ver=1.10.7
INFO[0000] loading components                            app_id=Identity-API instance=worker1 scope=dapr.runtime type=log ver=1.10.7
WARN[0000] A non-YAML Component file eshop-secrets.json was detected, it will not be loaded  app_id=Identity-API instance=worker1 scope=dapr.runtime.components type=log ver=1.10.7
WARN[0000] error processing component, daprd process will exit gracefully  app_id=Identity-API instance=worker1 scope=dapr.runtime type=log ver=1.10.7
FATA[0000] process component eshopondapr-secretstore error: [INIT_COMPONENT_FAILURE]: initialization error occurred for eshopondapr-secretstore (secretstores.local.file/v1): open /components/eshop-secrets.json: no such file or directory  app_id=Identity-API instance=worker1 scope=dapr.runtime type=log ver=1.10.7
❌  The daprd process exited with error code: exit status 1
⚠  Could not update sidecar metadata for cliPID: PUT http://127.0.0.1:3500/v1.0/metadata/cliPID giving up after 5 attempt(s): Put "http://127.0.0.1:3500/v1.0/metadata/cliPID": dial tcp 127.0.0.1:3500: connect: connection refused
ℹ️  Updating metadata for appPID: 19857
== APP == Unhandled exception. System.Threading.Tasks.TaskCanceledException: A task was canceled.
== APP ==    at Dapr.Client.DaprClientGrpc.WaitForSidecarAsync(CancellationToken cancellationToken)
== APP ==    at Dapr.Extensions.Configuration.DaprSecretStore.DaprSecretStoreConfigurationProvider.LoadAsync()
== APP ==    at Dapr.Extensions.Configuration.DaprSecretStore.DaprSecretStoreConfigurationProvider.Load()
== APP ==    at Microsoft.Extensions.Configuration.ConfigurationManager.AddSource(IConfigurationSource source)
== APP ==    at Microsoft.Extensions.Configuration.ConfigurationManager.Microsoft.Extensions.Configuration.IConfigurationBuilder.Add(IConfigurationSource source)
== APP ==    at Dapr.Extensions.Configuration.DaprSecretStoreConfigurationExtensions.AddDaprSecretStore(IConfigurationBuilder configurationBuilder, String store, DaprClient client, IReadOnlyDictionary`2 metadata)
== APP ==    at Microsoft.eShopOnDapr.Services.Identity.API.ProgramExtensions.AddCustomConfiguration(WebApplicationBuilder builder) in /home/wangpengzong/github/eShopOnDapr/src/Services/Identity/Identity.API/ProgramExtensions.cs:line 11
== APP ==    at Program.<Main>$(String[] args) in /home/wangpengzong/github/eShopOnDapr/src/Services/Identity/Identity.API/Program.cs:line 4
== APP ==    at Program.<Main>(String[] args)
❌  The App process exited with error code: exit status 134
⚠  Could not update sidecar metadata for appPID: PUT http://127.0.0.1:3500/v1.0/metadata/appPID giving up after 5 attempt(s): Put "http://127.0.0.1:3500/v1.0/metadata/appPID": dial tcp 127.0.0.1:3500: connect: connection refused
ℹ️  Updating metadata for app command: dotnet run --project src/Services/Identity/Identity.API/Identity.API.csproj
⚠  Could not update sidecar metadata for appCommand: PUT http://127.0.0.1:3500/v1.0/metadata/appCommand giving up after 5 attempt(s): Put "http://127.0.0.1:3500/v1.0/metadata/appCommand": dial tcp 127.0.0.1:3500: connect: connection refused
ℹ️  
terminated signal received: shutting down
❌  Error exiting Dapr: exit status 1
❌  Error exiting App: exit status 134
```

## Steps to Reproduce the Problem

```
dapr init
git clone https://github.com/dotnet-architecture/eShopOnDapr.git
cd eShopOnDapr
dapr run --resources-path ./dapr/components/ --config ./dapr/configuration/eshop-config.yaml --placement-host-address 50005 --dapr-http-port 3500 --dapr-grpc-port 50001  --app-port 80 --app-id Identity-API  -- dotnet run --project "src/Services/Identity/Identity.API/Identity.API.csproj"
```

## Release Note

RELEASE NOTE:

**Comment by halspang** [comment]
@spatxos - This isn't an SDK issue. The error you're seeing is coming from the component, but taking a look at this repo, it appears to be designed to be run with docker, not just from the command line like that. I'd recommend opening an issue in that repo if you continue to have trouble with it.
