### ISSUE TITLE
An error occurred when calling python Sidecar with net6 using dapr. python returned correctly, but net6 accepted the error

### ISSUE THREAD

**Issue by wxlnet** [dapr/dotnet-sdk#1132]
An error occurred when calling python Sidecar with net6 using dapr. python returned correctly, but net6 accepted the error
python  service
![image](https://github.com/dapr/dotnet-sdk/assets/65823238/080c2f22-ce65-447c-aa9d-8e2d36ef4214)
2023-08-10 18:55:12 127.0.0.1 - - [10/Aug/2023 10:55:12] "GET /dapr/config HTTP/1.1" 404 -
2023-08-10 18:56:41 127.0.0.1 - - [10/Aug/2023 10:56:41] "GET /daprtestjson HTTP/1.1" 200 -
2023-08-10 18:56:47 127.0.0.1 - - [10/Aug/2023 10:56:47] "GET /daprtestjson HTTP/1.1" 200 -
2023-08-10 18:57:04 127.0.0.1 - - [10/Aug/2023 10:57:04] "GET /daprtestjson HTTP/1.1" 200 -
2023-08-10 19:45:16 127.0.0.1 - - [10/Aug/2023 11:45:16] "GET /daprtestjson HTTP/1.1" 200 -
2023-08-10 19:45:20 127.0.0.1 - - [10/Aug/2023 11:45:20] "GET /daprtestjson HTTP/1.1" 200 -
2023-08-10 19:45:24 127.0.0.1 - - [10/Aug/2023 11:45:24] "GET /daprtest HTTP/1.1" 200 -
2023-08-10 20:14:50 127.0.0.1 - - [10/Aug/2023 12:14:50] "GET /TestGet HTTP/1.1" 404 -
2023-08-10 20:18:35 127.0.0.1 - - [10/Aug/2023 12:18:35] "GET /daprtestjson HTTP/1.1" 200 -
2023-08-10 20:24:43 127.0.0.1 - - [10/Aug/2023 12:24:43] "GET /daprtestjson HTTP/1.1" 200 -
2023-08-10 20:29:23 127.0.0.1 - - [10/Aug/2023 12:29:23] "GET /daprtestjson HTTP/1.1" 200 -
2023-08-10 20:29:32 127.0.0.1 - - [10/Aug/2023 12:29:32] "GET /daprtestjson HTTP/1.1" 200 -
2023-08-10 20:29:37 127.0.0.1 - - [10/Aug/2023 12:29:37] "GET /daprtest HTTP/1.1" 200 -
net service
![image](https://github.com/dapr/dotnet-sdk/assets/65823238/9063466f-2245-4ba8-a29e-ff69d9a94b1d)
Microsoft.AspNetCore.Server.Kestrel[13]
2023-08-10 20:29:32       Connection id "0HMSPJLHAPF8F", Request id "0HMSPJLHAPF8F:00000005": An unhandled exception was thrown by the application.
2023-08-10 20:29:32       Dapr.Client.InvocationException: An exception occurred while invoking method: 'daprtestjson' on app-id: 'pythontestservice'
2023-08-10 20:29:32        ---> System.Text.Json.JsonException: The JSON value could not be converted to System.Int32. Path: $.Name | LineNumber: 0 | BytePositionInLine: 22.
2023-08-10 20:29:32        ---> System.InvalidOperationException: Cannot get the value of a token type 'String' as a number.
2023-08-10 20:29:32          at System.Text.Json.Utf8JsonReader.TryGetInt32(Int32& value)
2023-08-10 20:29:32          at System.Text.Json.Utf8JsonReader.GetInt32()
2023-08-10 20:29:32          at System.Text.Json.Serialization.Converters.Int32Converter.Read(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options)
2023-08-10 20:29:32          at System.Text.Json.Serialization.Metadata.JsonPropertyInfo`1.ReadJsonAndSetMember(Object obj, ReadStack& state, Utf8JsonReader& reader)
2023-08-10 20:29:32          at System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1.OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
2023-08-10 20:29:32          at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
2023-08-10 20:29:32          at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
2023-08-10 20:29:32          --- End of inner exception stack trace ---
2023-08-10 20:29:32          at System.Text.Json.ThrowHelper.ReThrowWithPath(ReadStack& state, Utf8JsonReader& reader, Exception ex)
2023-08-10 20:29:32          at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
2023-08-10 20:29:32          at System.Text.Json.JsonSerializer.ReadCore[TValue](JsonConverter jsonConverter, Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
2023-08-10 20:29:32          at System.Text.Json.JsonSerializer.ReadCore[TValue](JsonReaderState& readerState, Boolean isFinalBlock, ReadOnlySpan`1 buffer, JsonSerializerOptions options, ReadStack& state, JsonConverter converterBase)
2023-08-10 20:29:32          at System.Text.Json.JsonSerializer.ContinueDeserialize[TValue](ReadBufferState& bufferState, JsonReaderState& jsonReaderState, ReadStack& readStack, JsonConverter converter, JsonSerializerOptions options)
2023-08-10 20:29:32          at System.Text.Json.JsonSerializer.ReadAllAsync[TValue](Stream utf8Json, JsonTypeInfo jsonTypeInfo, CancellationToken cancellationToken)
2023-08-10 20:29:32          at System.Net.Http.Json.HttpContentJsonExtensions.ReadFromJsonAsyncCore[T](HttpContent content, Encoding sourceEncoding, JsonSerializerOptions options, CancellationToken cancellationToken)
2023-08-10 20:29:32          at Dapr.Client.DaprClientGrpc.InvokeMethodAsync[TResponse](HttpRequestMessage request, CancellationToken cancellationToken)
2023-08-10 20:29:32          --- End of inner exception stack trace ---
2023-08-10 20:29:32          at Dapr.Client.DaprClientGrpc.InvokeMethodAsync[TResponse](HttpRequestMessage request, CancellationToken cancellationToken)
2023-08-10 20:29:32          at testService.Controllers.TestBaseServiceController.TestPythonjson() in D:\WorkCode\webapi\testService\Controllers\TestBaseServiceController.cs:line 199
2023-08-10 20:29:32          at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
2023-08-10 20:29:32          at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
2023-08-10 20:29:32          at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
2023-08-10 20:29:32          at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)

**Comment by halspang** [comment]
@wxlnet - That looks like it's having trouble with encoding/decoding the data. How does your python app encode it's response?

**Comment by wxlnet** [comment]
Thank you. Problem solved




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "dapr/dotnet-sdk"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年8月18日(星期五) 凌晨1:54
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [dapr/dotnet-sdk] An error occurred when calling python Sidecar with net6 using dapr. python returned correctly, but net6 accepted the error (Issue #1132)





 
@wxlnet - That looks like it's having trouble with encoding/decoding the data. How does your python app encode it's response?
