### ISSUE TITLE
Strongly typed client ActorProxy ignores JsonSerializerOptions

### ISSUE THREAD

**Issue by juselius** [dapr/dotnet-sdk#1138]
## Expected Behavior

When using actors with F# discriminated union types, I need to configure the ActorProxy client to use `JsonFSharpConverter()` for deserialization of the response body. I expect the following snippet to call the remote actor and return a properly deserialzied union case:

```fsharp
task {
       let dapr = ctx.GetService<DaprClient>()
       let opt = ActorProxyOptions()
       opt.JsonSerializerOptions <- dapr.JsonSerializerOptions
       let proxy = ActorProxy.Create<IMyActor>(ActorId.CreateRandom(), "MyActor", opt)
       return! proxy.Kaboom()
}
```
I have added the correct json serializer into the ASP.NET service collection with `AddDaprClient(...)`.

## Actual Behavior

Running the above snippet results in:

```
[13:40:02 ERR] checkPolicies: Dapr.DaprApiException: error invoke actor method: failed to cast response
    at Dapr.Actors.DaprHttpInteractor.SendAsyncHandleUnsuccessfulResponse(Func`1 requestFunc, String relativeUri, CancellationToken cancellationToken)
    at Dapr.Actors.DaprHttpInteractor.SendAsync(Func`1 requestFunc, String relativeUri, CancellationToken cancellationToken)
    at Dapr.Actors.DaprHttpInteractor.InvokeActorMethodWithRemotingAsync(ActorMessageSerializersManager serializersManager, IActorRequestMessage remotingRequestRequestMessage, CancellationToken cancellationToken)
    at Dapr.Actors.Communication.Client.ActorRemotingClient.InvokeAsync(IActorRequestMessage remotingRequestMessage, CancellationToken cancellationToken)
    at Dapr.Actors.Client.ActorProxy.InvokeMethodAsync(Int32 interfaceId, Int32 methodId, String methodName, IActorRequestMessageBody requestMsgBodyValue, CancellationToken cancellationToken)
    at Dapr.Actors.Client.ActorProxy.ContinueWithResult[TRetval](Int32 interfaceId, Int32 methodId, Task`1 task)
    at Api.Handlers.Pipe #1 input at line 263@263.MoveNext() in /home/jonas/src/Foo/Server/Api.fs:line 123
```

However, the following snippet works like expected:
```fsharp
task {
       ...
       let proxy = ActorProxy.DefaultProxyFactory.Create(ActorId.CreateRandom(), "MyActor", opt)
       return! proxy.InvokeMethodAsync<string option>("Kaboom")
}
```

From the stack trace it seems that the strongly-typed proxy implicitly calls the `InvokeMethodAsync()` defined on line 210 in [ActorProxy.cs](https://github.com/dapr/dotnet-sdk/blob/667dcaf44154bc41611bf3b19a048589eabe2ce8/src/Dapr.Actors/Client/ActorProxy.cs#L210), whereas the weakly-typed proxy explicitly calls `InvokeMethodAsync()` defined on [line 152](https://github.com/dapr/dotnet-sdk/blob/667dcaf44154bc41611bf3b19a048589eabe2ce8/src/Dapr.Actors/Client/ActorProxy.cs#L152). The latter correctly handles `JsonSerializerOptions`.

## Release Note

RELEASE NOTE: **FIX** Bug in .NET client SDK.

**Comment by halspang** [comment]
This is because the strongly typed actors always use DataContractSerializer. So, the options are actually a little misleading. 

This PR: https://github.com/dapr/dotnet-sdk/pull/1073, however did allow for a JSON serialization with the strongly typed actors. It'll come out in 1.12 or you can play with it locally. Let me know if it doesn't solve your problem and we can look into other solutions.

**Comment by WhitWaldo** [comment]
I'm going to go ahead and mark this as closed as the original poster hasn't circled back to indicate any additional problems with this and we're several versions removed.
