### ISSUE TITLE
error finding address for actor type DemoActor with id abc

### ISSUE THREAD

**Issue by ElderJames** [dapr/dotnet-sdk#117]
service output:

```ps
PS E:\learning\dapr\dotnet-sdk\samples\Actor\DemoActor> dapr run --port 3500 --app-id demo_actor --app-port 5001 dotnet run
Starting Dapr with id demo_actor. HTTP Port: 3500. gRPC Port: 56875
You're up and running! Both Dapr and your app logs will appear here.

== DAPR == time="2019-10-21T09:49:50+08:00" level=info msg="starting Dapr Runtime -- version 0.1.0 -- commit 4358565-dirty"
    == DAPR == time="2019-10-21T09:49:50+08:00" level=info msg="log level set to: info"
== DAPR == time="2019-10-21T09:49:50+08:00" level=info msg="standalone mode configured"
== DAPR == time="2019-10-21T09:49:50+08:00" level=info msg="dapr id: demo_actor"
    == DAPR == time="2019-10-21T09:49:50+08:00" level=info msg="loaded component messagebus (pubsub.redis)"
== DAPR == time="2019-10-21T09:49:50+08:00" level=info msg="loaded component statestore (state.redis)"
== DAPR == time="2019-10-21T09:49:50+08:00" level=info msg="application protocol: http. waiting on port 5001"
    == APP == Hosting environment: Development
    == APP == Content root path: E:\learning\dapr\dotnet-sdk\samples\Actor\DemoActor
== APP == Now listening on: http://localhost:5001
== APP == Application started. Press Ctrl+C to shut down.
    == DAPR == time="2019-10-21T09:49:56+08:00" level=info msg="application discovered on port 5001"
== DAPR == time="2019-10-21T09:49:56+08:00" level=fatal msg="listen tcp4 :3500: bind: Only one usage of each socket address (protocol/network address/port) is normally permitted."
== DAPR == time="2019-10-21T09:49:56+08:00" level=info msg="gRPC server is running on port 56875"
== DAPR == time="2019-10-21T09:49:56+08:00" level=info msg="local service entry announced"
== DAPR == time="2019-10-21T09:49:56+08:00" level=info msg="dapr initialized. Status: Running. Init Elapsed 5375.6975999999995ms"
== DAPR == time="2019-10-21T09:49:56+08:00" level=info msg="actors: established connection to placement service at localhost:6050"
== DAPR == time="2019-10-21T09:49:56+08:00" level=info msg="actors: placement order received: lock"
== DAPR == time="2019-10-21T09:49:56+08:00" level=info msg="actors: placement order received: update"
== DAPR == time="2019-10-21T09:49:56+08:00" level=info msg="actors: placement tables updated"
== DAPR == time="2019-10-21T09:49:56+08:00" level=info msg="actors: placement order received: unlock"
== DAPR == time="2019-10-21T09:49:56+08:00" level=info msg="actors: placement order received: lock"
```

client output:
```ps
PS E:\learning\dapr\dotnet-sdk\samples\Actor\ActorClient> dotnet run
Making call using actor proxy to save data.
Unhandled exception. Dapr.Actors.DaprException: error finding address for actor type DemoActor with id abc
   at Dapr.Actors.DaprHttpInteractor.SendAsyncHandleUnsuccessfulResponse(Func`1 requestFunc, String relativeUri, String requestId, CancellationToken cancellationToken) in E:\learning\dapr\dotnet-sdk\src\Dapr.Actors\DaprHttpInteractor.cs:line 449
   at Dapr.Actors.DaprHttpInteractor.SendAsync(Func`1 requestFunc, String relativeUri, String requestId, CancellationToken cancellationToken) in E:\learning\dapr\dotnet-sdk\src\Dapr.Actors\DaprHttpInteractor.cs:line 336
   at Dapr.Actors.DaprHttpInteractor.InvokeActorMethodWithRemotingAsync(ActorMessageSerializersManager serializersManager, IActorRequestMessage remotingRequestRequestMessage, CancellationToken cancellationToken) in E:\learning\dapr\dotnet-sdk\src\Dapr.Actors\DaprHttpInteractor.cs:line 164
   at Dapr.Actors.Communication.Client.ActorRemotingClient.InvokeAsync(IActorRequestMessage remotingRequestMessage, String methodName, CancellationToken cancellationToken) in E:\learning\dapr\dotnet-sdk\src\Dapr.Actors\Communication\Client\ActorRemotingClient.cs:line 41
   at Dapr.Actors.Client.ActorProxy.InvokeAsync(Int32 interfaceId, Int32 methodId, String methodName, IActorRequestMessageBody requestMsgBodyValue, CancellationToken cancellationToken) in E:\learning\dapr\dotnet-sdk\src\Dapr.Actors\Client\ActorProxy.cs:line 188
   at Dapr.Actors.Client.ActorProxy.ContinueWithResult[TRetval](Int32 interfaceId, Int32 methodId, Task`1 task) in E:\learning\dapr\dotnet-sdk\src\Dapr.Actors\Client\ActorProxy.cs:line 253
   at ActorClient.Program.Main(String[] args) in E:\learning\dapr\dotnet-sdk\samples\Actor\ActorClient\Program.cs:line 40
```

**Comment by amanbha** [comment]
Is something else running on port 3500? Did you run some other sample before this and that's still running?

**Comment by ElderJames** [comment]
I'm afraid not, because dapr is working.

**Comment by amanbha** [comment]
@ElderJames  I see following error in Dapr logs, so some other instance is listening on the port 3500, could you please check again.
== DAPR == time="2019-10-21T09:49:56+08:00" level=fatal msg="listen tcp4 :3500: bind: Only one usage of each socket address (protocol/network address/port) is normally permitted."

**Comment by amanbha** [comment]
@ElderJames  I am closing it based on the error in the logs pasted above as it looks like you have somethign else listening on port 3500.  Please feel free to reopen if you need more help from us.
