### ISSUE TITLE
Void methods on actors cannot be deserialized

### ISSUE THREAD

**Issue by RicardoNiepel** [dapr/dotnet-sdk#129]
## Expected Behavior

Methods on actors don't need to return anything.

## Actual Behavior

If using the strongly typed ActorProxy, the following exception is thrown: "System.Runtime.Serialization.SerializationException: There was an error deserializing the object of type WrappedMessageBody. Unexpected end of file. Following elements are not closed: ."

## Steps to Reproduce the Problem

Using void methods on an actor
```c#
public interface IMyActor : IActor
{
    Task DoingGreatThings();
}
```

Using
```c#
var proxy = ActorProxy.Create(actorID, actorType);
await proxy.InvokeAsync("DoingGreatThings");
```
succeeds

Using
```c#
var proxy = ActorProxy.Create<IMyActor>(actorID, actorType);
await proxy.DoingGreatThings();
```
throws exception
```
System.Runtime.Serialization.SerializationException: There was an error deserializing the object of type WrappedMessageBody. Unexpected end of file. Following elements are not closed: .
 ---> System.Xml.XmlException: Unexpected end of file. Following elements are not closed: .
   at System.Xml.XmlExceptionHelper.ThrowXmlException(XmlDictionaryReader reader, String res, String arg1, String arg2, String arg3)
   at System.Xml.XmlExceptionHelper.ThrowUnexpectedEndOfFile(XmlDictionaryReader reader)
   at System.Xml.XmlBufferReader.ReadBytes(Int32 count)
   at System.Xml.XmlBinaryReader.ReadName(StringHandle handle)
   at System.Xml.XmlBinaryReader.ReadNode()
   at System.Xml.XmlBinaryReader.Read()
   at System.Xml.XmlBaseReader.IsStartElement()
   at System.Xml.XmlBaseReader.IsStartElement(XmlDictionaryString localName, XmlDictionaryString namespaceUri)
   at System.Runtime.Serialization.XmlReaderDelegator.IsStartElement(XmlDictionaryString localname, XmlDictionaryString ns)
   at System.Runtime.Serialization.XmlObjectSerializer.IsRootElement(XmlReaderDelegator reader, DataContract contract, XmlDictionaryString name, XmlDictionaryString ns)
   at System.Runtime.Serialization.DataContractSerializer.InternalReadObject(XmlReaderDelegator xmlReader, Boolean verifyObjectName, DataContractResolver dataContractResolver)
   at System.Runtime.Serialization.XmlObjectSerializer.ReadObjectHandleExceptions(XmlReaderDelegator reader, Boolean verifyObjectName, DataContractResolver dataContractResolver)
   --- End of inner exception stack trace ---
   at System.Runtime.Serialization.XmlObjectSerializer.ReadObjectHandleExceptions(XmlReaderDelegator reader, Boolean verifyObjectName, DataContractResolver dataContractResolver)
   at System.Runtime.Serialization.XmlObjectSerializer.ReadObject(XmlDictionaryReader reader)
   at Dapr.Actors.Communication.ActorMessageBodyDataContractSerializationProvider.MemoryStreamMessageBodySerializer`2.Dapr.Actors.Communication.IActorResponseMessageBodySerializer.Deserialize(Stream messageBody)
   at Dapr.Actors.DaprHttpInteractor.InvokeActorMethodWithRemotingAsync(ActorMessageSerializersManager serializersManager, IActorRequestMessage remotingRequestRequestMessage, CancellationToken cancellationToken)
   at Dapr.Actors.Communication.Client.ActorRemotingClient.InvokeAsync(IActorRequestMessage remotingRequestMessage, String methodName, CancellationToken cancellationToken)
   at Dapr.Actors.Client.ActorProxy.InvokeAsync(Int32 interfaceId, Int32 methodId, String methodName, IActorRequestMessageBody requestMsgBodyValue, CancellationToken cancellationToken)
   at SamplePubSub.Ingress.Startup.<>c.<<Configure>g__Consent|3_1>d.MoveNext() in Startup.cs:line 63
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
```

**Comment by amanbha** [comment]
Thanks for reporting it @RicardoNiepel, we will take a look at it.

**Comment by amanbha** [comment]
@RicardoNiepel  I am not able to repro this, I am adding this scenario to the sample which is checked in this PR https://github.com/dapr/dotnet-sdk/pull/132

**Comment by RicardoNiepel** [comment]
I've tried to build a repo but this doesn't show up again.
Close it for now and reopen it with a repo next time.

**Comment by zaksnet** [comment]
I had the same error and what fixed it was switching from .NET 7 to .NET 6. 
NOTE: My actor's service was using .NET 6 and the gateway was .NET 7. I have not tested using .NET 7 on both services, in the end, the issue might have been that i was using different frameworks for each service but for now i assume that this was .NET 7 issue.
