### ISSUE TITLE
Problem in running "Dapr Actor Sample"

### ISSUE THREAD

**Issue by Shawn-Fan** [dapr/dotnet-sdk#159]
When I follow the instruction to run dotnet-sdk/samples/Actor on local dev machine at the first time, everything looks fine.  it looks like dapr should be running based on the docker container.
Recently, the code can not work, I try to figure it out. the strange thing is that dapr can work even without docker!! can you let me know how can i check if the dapr works properly or not?

**Comment by amanbha** [comment]
@Shawn-Fan Dapr runtime can run without docker, however for local Actor development you need docker as it runs a placement service(used by Actors) in a docker container. It also runs a redis docker container which is used by default by dapr cli to provide state & pubsub capabilities.
Could you pleases explain specific issues you are running into?

**Comment by Shawn-Fan** [comment]
The problem is for the example code under "dotnet-sdk/samples/Actor/"folder. At the first time, it can be run on the local dev machine when docker is running(The command "daps run --port 3500 --app-id demo_actor --app-port 5000 dotnet run " can be excuted successful), Actor service works fine, Actorclient running well. Without running docker, actor service and actor client can not work properly.
But recently, I try the same  code above, same steps as before, everything is fine but actor client can not connect the actor service. I turn off the docker, run the actor service ((The command "daps run --port 3500 --app-id demo_actor --app-port 5000 dotnet run ") can be excuted successful so the question arised.

**Comment by amanbha** [comment]
@Shawn-Fan  for using Actors, you would need placement service. And by placement service is setup to run in a docker container when you do dapr init. Without the placement service, clients will not be able to discover service which hosts an actor type.

**Comment by Shawn-Fan** [comment]
@amanbha 

Fallowng is the exciting result:
docker ps
CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS              PORTS                      NAMES
77d38ee4b04b        daprio/dapr         "./placement"            4 hours ago         Up 9 seconds        0.0.0.0:50005->50005/tcp   dapr_placement
41de22934a5d        redis               "docker-entrypoint.s…"   4 days ago          Up 9 seconds        0.0.0.0:6379->6379/tcp     friendly_northcutt
MacBook:DemoActor ia$ dapr run --port 3500 --app-id demo_actor --app-port 5000 dotnet run
ℹ️  Starting Dapr with id demo_actor. HTTP Port: 3500. gRPC Port: 63497
✅  You're up and running! Both Dapr and your app logs will appear here.

== DAPR == time="2019-11-18T13:57:28-07:00" level=info msg="starting Dapr Runtime -- version 0.2.0 -- commit c75b111"
== DAPR == time="2019-11-18T13:57:28-07:00" level=info msg="log level set to: info"
== DAPR == time="2019-11-18T13:57:28-07:00" level=info msg="standalone mode configured"
== DAPR == time="2019-11-18T13:57:28-07:00" level=info msg="dapr id: demo_actor"
== DAPR == time="2019-11-18T13:57:28-07:00" level=info msg="loaded component messagebus (pubsub.redis)"
== DAPR == time="2019-11-18T13:57:28-07:00" level=info msg="loaded component statestore (state.redis)"
== DAPR == time="2019-11-18T13:57:28-07:00" level=info msg="application protocol: http. waiting on port 5000"
== APP == Hosting environment: Development
== APP == Content root path: /Users/ian/Desktop/dotnet-sdk-master/samples/Actor/DemoActor
== APP == Now listening on: http://localhost:5001
== APP == Application started. Press Ctrl+C to shut down.
g="loaded component statestore (state.redis)"
== DAPR == time="2019-11-18T13:57:28-07:00" level=info msg="application protocol: http. waiting on port 5000"
== APP == Hosting environment: Development
== APP == Content root path: /Users/ian/Desktop/dotnet-sdk-master/samples/Actor/DemoActor
== APP == Now listening on: http://localhost:5001
== APP == Application started. Press Ctrl+C to shut down.

After running service client:
MacBook:ActorClient ia$ dotnet run
Making call using actor proxy to save data.
ERROR: DaprHttpInteractor:  System.Net.Http.HttpRequestException: Connection refused
 ---> System.Net.Sockets.SocketException (61): Connection refused
   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean allowHttp2, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttpConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at Dapr.Actors.DaprHttpInteractor.SendAsyncHandleSecurityExceptions(Func`1 requestFunc, CancellationToken cancellationToken) in /Users/ian/Desktop/dotnet-sdk-master/src/Dapr.Actors/DaprHttpInteractor.cs:line 479
Unhandled exception. System.Net.Http.HttpRequestException: Connection refused
 ---> System.Net.Sockets.SocketException (61): Connection refused
   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean allowHttp2, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttpConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at Dapr.Actors.DaprHttpInteractor.SendAsyncHandleSecurityExceptions(Func`1 requestFunc, CancellationToken cancellationToken) in /Users/ian/Desktop/dotnet-sdk-master/src/Dapr.Actors/DaprHttpInteractor.cs:line 479
   at Dapr.Actors.DaprHttpInteractor.SendAsyncHandleUnsuccessfulResponse(Func`1 requestFunc, String relativeUri, String requestId, CancellationToken cancellationToken) in /Users/ian/Desktop/dotnet-sdk-master/src/Dapr.Actors/DaprHttpInteractor.cs:line 415
   at Dapr.Actors.DaprHttpInteractor.SendAsync(Func`1 requestFunc, String relativeUri, String requestId, CancellationToken cancellationToken) in /Users/ian/Desktop/dotnet-sdk-master/src/Dapr.Actors/DaprHttpInteractor.cs:line 336
   at Dapr.Actors.DaprHttpInteractor.InvokeActorMethodWithRemotingAsync(ActorMessageSerializersManager serializersManager, IActorRequestMessage remotingRequestRequestMessage, CancellationToken cancellationToken) in /Users/ian/Desktop/dotnet-sdk-master/src/Dapr.Actors/DaprHttpInteractor.cs:line 164
   at Dapr.Actors.Communication.Client.ActorRemotingClient.InvokeAsync(IActorRequestMessage remotingRequestMessage, String methodName, CancellationToken cancellationToken) in /Users/ian/Desktop/dotnet-sdk-master/src/Dapr.Actors/Communication/Client/ActorRemotingClient.cs:line 40
   at Dapr.Actors.Client.ActorProxy.InvokeAsync(Int32 interfaceId, Int32 methodId, String methodName, IActorRequestMessageBody requestMsgBodyValue, CancellationToken cancellationToken) in /Users/ian/Desktop/dotnet-sdk-master/src/Dapr.Actors/Client/ActorProxy.cs:line 186
   at ActorClient.Program.Main(String[] args) in /Users/ian/Desktop/dotnet-sdk-master/samples/Actor/ActorClient/Program.cs:line 39
   at ActorClient.Program.<Main>(String[] args)

**Comment by amanbha** [comment]
@Shawn-Fan  Thanks for reporting the issue, I believe the sample doc is slightly incorrect as the app is running on port 5001. I will update it. Could you please try and run the actor service as dapr run --port 3500 --app-id demo_actor --app-port 5001 dotnet run

**Comment by Shawn-Fan** [comment]
Thanks! It works.

**Comment by codeputer** [comment]
Why would the application run on 5001 when the app-port was specified as 5000?

Just a question as I was playing with this the other day, and noticed that I only got a response on 5001...

In the documentation I always try and document the why, not the how.  For example,
Because the -app_port number is set to 5000, interaction will occur.
So
dapr run --port 3500 --app-id demo_actor --app-port 5001 dotnet run

Is much better in IMO, rather than just the line which we all cut and past.

As I'm new to Docker, I'm wondering why the  --port is specified, as from the application side, we never do anything with it - why is it there?  My assumption is that it's the port that is used to communicate inside Docker, and the app-port is the port we used to communicate from outside docker.

Regards,
Richard

**Comment by amanbha** [comment]
@codeputer I believe you wanted to say Dapr instead of Docker. 
The app-port is the parameter to tell Dapr on what port the application will be listening. 
Dapr and app both communicate with each other over http/grpc. --port is the port used by dapr for its http server. --app-port is the port at which app will be listening.

**Comment by codeputer** [comment]
Thanks and your right - I meant Dapr...

So why would the application respond on  5001 when the app-port was specified to be 5000

Did I miss something?

R

**Comment by amanbha** [comment]
@codeputer --app-port is just telling dapr that application will be listening on 5001, its not configuring app to run on 5001. The port logic is for the application to decide. For more info, please see: https://github.com/dapr/cli#launch-dapr-and-your-app
