### ISSUE TITLE
Running an actor service using dapr run and daprd produces different results

### ISSUE THREAD

**Issue by mareklinka** [dapr/dotnet-sdk#297]
Hello. I followed the ASP.NET Core Actor sample and created a very simple actor using F#. When running the code using `dapr run` (as mentioned in the sample), everything works as expected. However, when I run the sample using `daprd` (because I want to be able to launch the service together with other DAPR-enabled apps and debug them using VSCode), I always get an exception.

Actor code:
``` fsharp
open System
open Dapr.Actors;
open Dapr.Actors.Runtime;
open DotNetBa.Dapr.Common
open System.Threading.Tasks;

type FancyActor(actorService: ActorService, actorId: ActorId) =
    inherit Actor(actorService, actorId)

    member _.StateManager = base.StateManager

    override this.OnActivateAsync() : Task =
        let message = this.Id.ToString() |> sprintf "Actor %s is starting"

        Console.WriteLine(message)
        Task.CompletedTask

    interface IFancyActor with
        member this.PerformComplexCalculation(state: Models.FancyActorState): Task<Models.FancyActorState> =
            async {
                Console.WriteLine("Actor is doing work")
                let! _ = this.StateManager.AddOrUpdateStateAsync("my_data", state, fun _ _ -> state) |> Async.AwaitTask
                let! current = this.StateManager.GetStateAsync<Models.FancyActorState>("my_data") |> Async.AwaitTask

                return current
            } |> Async.StartAsTask
```

DAPR RUN command:
```
dapr run --port 3503 --app-id actors --app-port 5003 dotnet run

== DAPR == time="2020-05-03T09:07:00.7451164+02:00" level=info msg="starting Dapr Runtime -- version 0.6.0 -- commit e99f712-dirty" app_id=actors instance=Computer scope=dapr.runtime type=log ver=0.6.0
== DAPR == time="2020-05-03T09:07:00.7451164+02:00" level=info msg="starting Dapr Runtime -- version 0.6.0 -- commit e99f712-dirty" app_id=actors instance=Computer scope=dapr.runtime type=log ver=0.6.0
== DAPR == time="2020-05-03T09:07:00.7451164+02:00" level=info msg="log level set to: info" app_id=actors instance=Computer scope=dapr.runtime type=log ver=0.6.0
== DAPR == time="2020-05-03T09:07:00.7451164+02:00" level=info msg="metrics server started on :60415/" app_id=actors instance=Computer scope=dapr.metrics type=log ver=0.6.0
== DAPR == time="2020-05-03T09:07:00.9941168+02:00" level=info msg="loading default configuration" app_id=actors instance=Computer scope=dapr.runtime type=log ver=0.6.0
== DAPR == time="2020-05-03T09:07:00.9941168+02:00" level=info msg="standalone mode configured" app_id=actors instance=Computer scope=dapr.runtime type=log ver=0.6.0
== DAPR == time="2020-05-03T09:07:00.9941168+02:00" level=info msg="dapr id: actors" app_id=actors instance=Computer scope=dapr.runtime type=log ver=0.6.0
== DAPR == time="2020-05-03T09:07:00.9941168+02:00" level=info msg="mTLS is disabled. Skipping certificate request and tls validation" app_id=actors instance=Computer scope=dapr.runtime type=log ver=0.6.0
== DAPR == time="2020-05-03T09:07:00.9961172+02:00" level=info msg="found component statestore (state.redis)" app_id=actors instance=Computer scope=dapr.runtime type=log ver=0.6.0
== DAPR == time="2020-05-03T09:07:00.9961172+02:00" level=info msg="found component messagebus (pubsub.redis)" app_id=actors instance=Computer scope=dapr.runtime type=log ver=0.6.0
== DAPR == time="2020-05-03T09:07:00.9961172+02:00" level=info msg="application protocol: http. waiting on port 5003.  This will block until the app is listening on that port." app_id=actors instance=Computer scope=dapr.runtime type=log ver=0.6.0
== APP == info: Microsoft.Hosting.Lifetime[0]
== APP ==       Now listening on: http://localhost:5003
== APP == info: Microsoft.Hosting.Lifetime[0]
== APP ==       Application started. Press Ctrl+C to shut down.
== APP == info: Microsoft.Hosting.Lifetime[0]
== APP ==       Hosting environment: Development
== APP == info: Microsoft.Hosting.Lifetime[0]
== APP ==       Content root path: C:\Source\Personal\dotnetba-dapr\src\DotNetBa.Dapr.ActorService
== DAPR == time="2020-05-03T09:07:02.6501168+02:00" level=info msg="application discovered on port 5003" app_id=actors instance=Computer scope=dapr.runtime type=log ver=0.6.0
== DAPR == time="2020-05-03T09:07:02.6861173+02:00" level=info msg="application configuration loaded" app_id=actors instance=Computer scope=dapr.runtime type=log ver=0.6.0
== DAPR == time="2020-05-03T09:07:02.6971168+02:00" level=info msg="app is subscribed to the following topics: []" app_id=actors instance=Computer scope=dapr.runtime type=log ver=0.6.0
== DAPR == time="2020-05-03T09:07:02.6971168+02:00" level=info msg="Initialized service discovery to standalone" app_id=actors instance=Computer scope=dapr.runtime type=log ver=0.6.0
== DAPR == time="2020-05-03T09:07:02.6971168+02:00" level=info msg="actor runtime started. actor idle timeout: 1h0m0s. actor scan interval: 30s" app_id=actors instance=Computer scope=dapr.runtime.actor type=log ver=0.6.0
== DAPR == time="2020-05-03T09:07:02.6971168+02:00" level=info msg="starting connection attempt to placement service at localhost:6050" app_id=actors instance=Computer scope=dapr.runtime.actor type=log ver=0.6.0
== DAPR == time="2020-05-03T09:07:02.6971168+02:00" level=info msg="enabled metrics grpc middleware" app_id=actors instance=Computer scope=dapr.runtime.grpc type=log ver=0.6.0
== DAPR == time="2020-05-03T09:07:02.6971168+02:00" level=info msg="API gRPC server is running on port 60414" app_id=actors instance=Computer scope=dapr.runtime type=log ver=0.6.0
== DAPR == time="2020-05-03T09:07:02.6971168+02:00" level=info msg="enabled metrics grpc middleware" app_id=actors instance=Computer scope=dapr.runtime.grpc type=log ver=0.6.0
== DAPR == time="2020-05-03T09:07:02.6971168+02:00" level=info msg="internal gRPC server is running on port 60422" app_id=actors instance=Computer scope=dapr.runtime type=log ver=0.6.0
== DAPR == time="2020-05-03T09:07:02.6971168+02:00" level=info msg="enabled cors http middleware" app_id=actors instance=Computer scope=dapr.runtime.http type=log ver=0.6.0
== DAPR == time="2020-05-03T09:07:02.6971168+02:00" level=info msg="enabled proxy http middleware" app_id=actors instance=Computer scope=dapr.runtime.http type=log ver=0.6.0
== DAPR == time="2020-05-03T09:07:02.6971168+02:00" level=info msg="enabled metrics http middleware" app_id=actors instance=Computer scope=dapr.runtime.http type=log ver=0.6.0
== DAPR == time="2020-05-03T09:07:02.6971168+02:00" level=info msg="http server is running on port 3503" app_id=actors instance=Computer scope=dapr.runtime type=log ver=0.6.0
== DAPR == time="2020-05-03T09:07:02.6971168+02:00" level=info msg="local service entry announced" app_id=actors instance=Computer scope=dapr.runtime type=log ver=0.6.0
== DAPR == time="2020-05-03T09:07:02.6971168+02:00" level=info msg="dapr initialized. Status: Running. Init Elapsed 1702.9999999999998ms" app_id=actors instance=Computer scope=dapr.runtime type=log ver=0.6.0
== DAPR == time="2020-05-03T09:07:02.6991184+02:00" level=info msg="established connection to placement service at localhost:6050" app_id=actors instance=Computer scope=dapr.runtime.actor type=log ver=0.6.0
== DAPR == time="2020-05-03T09:07:02.7001163+02:00" level=info msg="placement order received: lock" app_id=actors instance=Computer scope=dapr.runtime.actor type=log ver=0.6.0
== DAPR == time="2020-05-03T09:07:02.7001163+02:00" level=info msg="placement order received: update" app_id=actors instance=Computer scope=dapr.runtime.actor type=log ver=0.6.0
== DAPR == time="2020-05-03T09:07:02.7001163+02:00" level=info msg="actors: placement tables updated" app_id=actors instance=Computer scope=dapr.runtime.actor type=log ver=0.6.0
== DAPR == time="2020-05-03T09:07:02.7001163+02:00" level=info msg="placement order received: unlock" app_id=actors instance=Computer scope=dapr.runtime.actor type=log ver=0.6.0
== DAPR == time="2020-05-03T09:07:02.7001163+02:00" level=info msg="placement order received: lock" app_id=actors instance=Computer scope=dapr.runtime.actor type=log ver=0.6.0
== DAPR == time="2020-05-03T09:07:02.7001163+02:00" level=info msg="placement order received: update" app_id=actors instance=Computer scope=dapr.runtime.actor type=log ver=0.6.0
== DAPR == time="2020-05-03T09:07:02.7001163+02:00" level=info msg="actors: placement tables updated" app_id=actors instance=Computer scope=dapr.runtime.actor type=log ver=0.6.0
== DAPR == time="2020-05-03T09:07:02.7001163+02:00" level=info msg="placement order received: unlock" app_id=actors instance=Computer scope=dapr.runtime.actor type=log ver=0.6.0
Updating metadata for app command: dotnet run
You're up and running! Both Dapr and your app logs will appear here.
```

DAPRD command:
```
daprd --app-id "actors" --app-port "5003" --components-path "[shortened]\[project folder]\components" --dapr-grpc-port "50004" --dapr-http-port "3503" --metrics-port "9093" --placement-address "localhost:6050"

time="2020-05-03T09:09:01.6771491+02:00" level=info msg="starting Dapr Runtime -- version 0.6.0 -- commit e99f712-dirty" app_id=actors instance=Computer scope=dapr.runtime type=log ver=0.6.0
time="2020-05-03T09:09:01.6771491+02:00" level=info msg="log level set to: info" app_id=actors instance=Computer scope=dapr.runtime type=log ver=0.6.0
time="2020-05-03T09:09:01.6771491+02:00" level=info msg="metrics server started on :9093/" app_id=actors instance=Computer scope=dapr.metrics type=log ver=0.6.0
time="2020-05-03T09:09:01.9181195+02:00" level=info msg="loading default configuration" app_id=actors instance=Computer scope=dapr.runtime type=log ver=0.6.0
time="2020-05-03T09:09:01.9181195+02:00" level=info msg="standalone mode configured" app_id=actors instance=Computer scope=dapr.runtime type=log ver=0.6.0
time="2020-05-03T09:09:01.9181195+02:00" level=info msg="dapr id: actors" app_id=actors instance=Computer scope=dapr.runtime type=log ver=0.6.0
time="2020-05-03T09:09:01.9181195+02:00" level=info msg="mTLS is disabled. Skipping certificate request and tls validation" app_id=actors instance=Computer scope=dapr.runtime type=log ver=0.6.0
time="2020-05-03T09:09:01.9201206+02:00" level=info msg="found component messagebus (pubsub.redis)" app_id=actors instance=Computer scope=dapr.runtime type=log ver=0.6.0
time="2020-05-03T09:09:01.9201206+02:00" level=info msg="found component statestore (state.redis)" app_id=actors instance=Computer scope=dapr.runtime type=log ver=0.6.0
time="2020-05-03T09:09:01.9201206+02:00" level=info msg="application protocol: http. waiting on port 5003.  This will block until the app is listening on that port." app_id=actors instance=Computer scope=dapr.runtime type=log ver=0.6.0
time="2020-05-03T09:09:03.0221194+02:00" level=info msg="application discovered on port 5003" app_id=actors instance=Computer scope=dapr.runtime type=log ver=0.6.0
time="2020-05-03T09:09:03.0871196+02:00" level=info msg="application configuration loaded" app_id=actors instance=Computer scope=dapr.runtime type=log ver=0.6.0
time="2020-05-03T09:09:03.1001195+02:00" level=info msg="app is subscribed to the following topics: []" app_id=actors instance=Computer scope=dapr.runtime type=log ver=0.6.0
time="2020-05-03T09:09:03.1001195+02:00" level=info msg="Initialized service discovery to standalone" app_id=actors instance=Computer scope=dapr.runtime type=log ver=0.6.0
time="2020-05-03T09:09:03.1001195+02:00" level=info msg="actor runtime started. actor idle timeout: 1h0m0s. actor scan interval: 30s" app_id=actors instance=Computer scope=dapr.runtime.actor type=log ver=0.6.0
time="2020-05-03T09:09:03.1001195+02:00" level=info msg="starting connection attempt to placement service at localhost:6050" app_id=actors instance=Computer scope=dapr.runtime.actor type=log ver=0.6.0
time="2020-05-03T09:09:03.1001195+02:00" level=info msg="enabled metrics grpc middleware" app_id=actors instance=Computer scope=dapr.runtime.grpc type=log ver=0.6.0
time="2020-05-03T09:09:03.1001195+02:00" level=info msg="API gRPC server is running on port 50004" app_id=actors instance=Computer scope=dapr.runtime type=log ver=0.6.0
time="2020-05-03T09:09:03.1001195+02:00" level=info msg="enabled metrics grpc middleware" app_id=actors instance=Computer scope=dapr.runtime.grpc type=log ver=0.6.0
time="2020-05-03T09:09:03.1001195+02:00" level=info msg="internal gRPC server is running on port 60685" app_id=actors instance=Computer scope=dapr.runtime type=log ver=0.6.0
time="2020-05-03T09:09:03.1001195+02:00" level=info msg="enabled cors http middleware" app_id=actors instance=Computer scope=dapr.runtime.http type=log ver=0.6.0
time="2020-05-03T09:09:03.1001195+02:00" level=info msg="enabled proxy http middleware" app_id=actors instance=Computer scope=dapr.runtime.http type=log ver=0.6.0
time="2020-05-03T09:09:03.1001195+02:00" level=info msg="enabled metrics http middleware" app_id=actors instance=Computer scope=dapr.runtime.http type=log ver=0.6.0
time="2020-05-03T09:09:03.1001195+02:00" level=info msg="http server is running on port 3503" app_id=actors instance=Computer scope=dapr.runtime type=log ver=0.6.0
time="2020-05-03T09:09:03.1001195+02:00" level=info msg="local service entry announced" app_id=actors instance=Computer scope=dapr.runtime type=log ver=0.6.0
time="2020-05-03T09:09:03.1001195+02:00" level=info msg="dapr initialized. Status: Running. Init Elapsed 1182ms" app_id=actors instance=Computer scope=dapr.runtime type=log ver=0.6.0
time="2020-05-03T09:09:03.1021194+02:00" level=info msg="established connection to placement service at localhost:6050" app_id=actors instance=Computer scope=dapr.runtime.actor type=log ver=0.6.0
time="2020-05-03T09:09:03.1031197+02:00" level=info msg="placement order received: lock" app_id=actors instance=Computer scope=dapr.runtime.actor type=log ver=0.6.0
time="2020-05-03T09:09:03.1031197+02:00" level=info msg="placement order received: update" app_id=actors instance=Computer scope=dapr.runtime.actor type=log ver=0.6.0
time="2020-05-03T09:09:03.1031197+02:00" level=info msg="actors: placement tables updated" app_id=actors instance=Computer scope=dapr.runtime.actor type=log ver=0.6.0
time="2020-05-03T09:09:03.1031197+02:00" level=info msg="placement order received: unlock" app_id=actors instance=Computer scope=dapr.runtime.actor type=log ver=0.6.0
time="2020-05-03T09:09:03.1031197+02:00" level=info msg="placement order received: lock" app_id=actors instance=Computer scope=dapr.runtime.actor type=log ver=0.6.0
time="2020-05-03T09:09:03.1041193+02:00" level=info msg="placement order received: update" app_id=actors instance=Computer scope=dapr.runtime.actor type=log ver=0.6.0
time="2020-05-03T09:09:03.1041193+02:00" level=info msg="actors: placement tables updated" app_id=actors instance=Computer scope=dapr.runtime.actor type=log ver=0.6.0
time="2020-05-03T09:09:03.1041193+02:00" level=info msg="placement order received: unlock" app_id=actors instance=Computer scope=dapr.runtime.actor type=log ver=0.6.0
```

## Expected Behavior
Running 
```
POST http://127.0.0.1:3503/v1.0/actors/FancyActor/a/method/PerformComplexCalculation
{
    "Data": "some data"
}
```
using the DAPR RUN command should behave the same as running using DAPRD command (the actor stores the provided data into the actor store and echoes it back).

## Actual Behavior
Running
```
POST http://127.0.0.1:3503/v1.0/actors/FancyActor/a/method/PerformComplexCalculation
{
    "Data": "some data"
}
```
using the DAPR RUN command works correctly but running the the same using DAPRD produces an exception:

```
{
    "errorCode": "ERR_ACTOR_INVOKE_METHOD",
    "message": "error from actor service: System.AggregateException: One or more errors occurred. (No connection could be made because the target machine actively refused it.)
 ---> System.Net.Http.HttpRequestException: No connection could be made because the target machine actively refused it.
 ---> System.Net.Sockets.SocketException (10061): No connection could be made because the target machine actively refused it.
   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean allowHttp2, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttpConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.DiagnosticsHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at Dapr.Actors.DaprHttpInteractor.SendAsyncHandleSecurityExceptions(Func`1 requestFunc, CancellationToken cancellationToken)
   at Dapr.Actors.DaprHttpInteractor.SendAsyncHandleUnsuccessfulResponse(Func`1 requestFunc, String relativeUri, String requestId, CancellationToken cancellationToken)
   at Dapr.Actors.DaprHttpInteractor.SendAsync(Func`1 requestFunc, String relativeUri, String requestId, CancellationToken cancellationToken)
   at Dapr.Actors.DaprHttpInteractor.GetStateAsync(String actorType, String actorId, String keyName, CancellationToken cancellationToken)
   at Dapr.Actors.Runtime.DaprStateProvider.TryLoadStateAsync[T](String actorType, String actorId, String stateName, CancellationToken cancellationToken)
   at Dapr.Actors.Runtime.ActorStateManager.AddOrUpdateStateAsync[T](String stateName, T addValue, Func`3 updateValueFactory, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at CallSite.Target(Closure , CallSite , Object )
   at Dapr.Actors.Runtime.ActorManager.<>c__DisplayClass15_0.<<DispatchWithoutRemotingAsync>g__RequestFunc|0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Dapr.Actors.Runtime.ActorManager.DispatchInternalAsync[T](ActorId actorId, ActorMethodContext actorMethodContext, Func`3 actorFunc, CancellationToken cancellationToken)
   at Dapr.Actors.Runtime.ActorManager.DispatchInternalAsync[T](ActorId actorId, ActorMethodContext actorMethodContext, Func`3 actorFunc, CancellationToken cancellationToken)
   at Dapr.Actors.Runtime.ActorManager.DispatchWithoutRemotingAsync(ActorId actorId, String actorMethodName, Stream requestBodyStream, Stream responseBodyStream, CancellationToken cancellationToken)
   at Dapr.Actors.AspNetCore.RouterBuilderExtensions.<>c.<<AddActorMethodRoute>b__4_0>d.MoveNext()"
}
```
The error message and stack tell me that the state store is unable to connect to the actal storage provider (which is the default redis which is enabled in standalone mode). Both commands should also use exactly the same components (just the default ones created but `dapr run` - redis for both pubsub and state store).

It's entirely possible I'm missing some piece of configuration for the DAPRD command but this seems like something that should work as currently configured.

If desired, I can publish the repro code to github.

**Comment by amanbha** [comment]
When you launch daprd and app separately without the cli dapr run command, the app doesnt know about the dapr port. By default the SDK makes call into dapr runtime on port 3500 or it uses port specified in env var DAPR_HTTP_PORT.
So se the env var to the port used by daprd for http so that actor app can use it OR run daprd to use 3500 as http port.

**Comment by mareklinka** [comment]
Ah, makes sense. My setup is a little more complex than just one app - I'm trying to debug several DAPR applications using VSCode and the DAPR extension so I assumed this will get handled by the extension but apparently not. Setting the appropriate env. variables solved the issue.

Thanks!
