### ISSUE TITLE
GetStateAsync/GetStateEntryAsync works when using redis but fails with SQL Server

### ISSUE THREAD

**Issue by mareklinka** [dapr/dotnet-sdk#298]
I have a small DAPR-enabled service which I originally wrote against the default redis state store. With that, the code worked fine. When I switched the state store to SQL Server, reading from the store started throwing exceptions.

Code:
``` csharp
[HttpPost]
[Route("register")]
public async Task<IActionResult> Register([FromBody] RegistrationRequest model,
                                            [FromServices] DaprClient dapr,
                                            CancellationToken cancellationToken)
{
    var profile = new UserProfile { Name = model.Username, PhoneNumber = model.Phone };

    await dapr.SaveStateAsync(Storage.SqlName, "test", profile, cancellationToken: cancellationToken)
                .ConfigureAwait(false);

    return Ok();
}

[HttpPost]
[Route("login")]
public async Task<LoginResponse> Login([FromBody] LoginRequest model,
                                        [FromServices] DaprClient dapr,
                                        CancellationToken cancellationToken)
{
    var profile = await dapr.GetStateEntryAsync<UserProfile>(Storage.SqlName,
                                                                "test",
                                                                cancellationToken: cancellationToken)
                            .ConfigureAwait(false);

    if (profile.Value is null)
    {
        return new LoginResponse { IsSuccess = false };
    }

    return new LoginResponse
    {
        IsSuccess = true,
        Roles = new[] { "role_1", "role_x" },
        Username = model.Username
    };
}
```

## Expected Behavior
Calling the `Login` method should succeed.

## Actual Behavior
Calling the `Register` method succeeds and persists the data to the SQL database:
![image](https://user-images.githubusercontent.com/7479226/80942860-29b5db80-8de6-11ea-9038-6a8fcefb91ca.png)

Subsequently calling the `Login` method throws an exception in `GetStateEntryAsync`:
```
System.Text.Json.JsonException: The JSON value could not be converted to DotNetBa.Dapr.Common.Models.UserProfile. Path: $ | LineNumber: 0 | BytePositionInLine: 58.
   at System.Text.Json.ThrowHelper.ThrowJsonException_DeserializeUnableToConvertValue(Type propertyType)
   at System.Text.Json.JsonPropertyInfoNotNullable`4.OnRead(ReadStack& state, Utf8JsonReader& reader)
   at System.Text.Json.JsonPropertyInfo.Read(JsonTokenType tokenType, ReadStack& state, Utf8JsonReader& reader)
   at System.Text.Json.JsonSerializer.ReadCore(JsonSerializerOptions options, Utf8JsonReader& reader, ReadStack& readStack)
   at System.Text.Json.JsonSerializer.ReadCore(Type returnType, JsonSerializerOptions options, Utf8JsonReader& reader)
   at System.Text.Json.JsonSerializer.Deserialize(String json, Type returnType, JsonSerializerOptions options)
   at System.Text.Json.JsonSerializer.Deserialize[TValue](String json, JsonSerializerOptions options)
   at Dapr.Client.DaprClientGrpc.GetStateAndETagAsync[TValue](String storeName, String key, Nullable`1 consistencyMode, CancellationToken cancellationToken)
   at Dapr.Client.DaprClient.GetStateEntryAsync[TValue](String storeName, String key, Nullable`1 consistencyMode, CancellationToken cancellationToken)
   at DotNetBa.Dapr.UserService.Controllers.LoginController.Login(LoginRequest model, DaprClient dapr, CancellationToken cancellationToken) in C:\Source\Personal\dotnetba-dapr\src\DotNetBa.Dapr.UserService\Controllers\LoginController.cs:line 27
   at lambda_method(Closure , Object )
   at Microsoft.Extensions.Internal.ObjectMethodExecutorAwaitable.Awaiter.GetResult()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
```

If I swap the target store for redis, the same code works as expected.

**Comment by mareklinka** [comment]
I took a closer look at the differences between the two stores:

Redis:
```
GET http://localhost:3501/v1.0/state/statestore/test

Response:
{
  "name": "test",
  "phoneNumber": "5724942286"
}
```

SQL Server:
```
GET http://localhost:3501/v1.0/state/sql-server/test

Response:
eyJuYW1lIjoidGVzdCIsInBob25lTnVtYmVyIjoiNDY5MjU3MDc0MSJ9
```

In the SQL Server's case the response is a base64-encoded JSON which translates to `{"name":"test","phoneNumber":"4692570741"}`.

Now I'm starting to think this might be an issue with the SQL Server DAPR component.

**Comment by mareklinka** [comment]
I just tried to invoke the state store API via DAPR's HTTP interface instead of the SDK.
```
POST http://localhost:3501/v1.0/state/sql-server

[
  {
    "key": "test",
    "value":
    {
      "name": "test",
      "phone": "12390712398"
    }
  }	
]

```

This is the result:
![image](https://user-images.githubusercontent.com/7479226/80949817-06def380-8df5-11ea-80cf-6f30be58011b.png)

Then:
```
GET http://localhost:3501/v1.0/state/sql-server/test

{
  "name": "test",
  "phone": "12390712398"
}
```
This is exactly correct. It seems to me that the SDK is performing some additional encoding and this encoding is not reversed before JSON deserialization is attempted in `GetStateEntryAsync`.

**Comment by mareklinka** [comment]
Well, I cloned the repo and debugged into the `DaprClientGrpc` to see what's happening there and it all looks good. The `ConvertToAnyAsync` works as I would expect and for my test data, produces a `ByteString` of length 40:
![image](https://user-images.githubusercontent.com/7479226/80959716-a907d700-8e07-11ea-9552-a1edc211e526.png)

However, when I get the value back from SQL Server, I get back a length of 58:
![image](https://user-images.githubusercontent.com/7479226/80959816-dfdded00-8e07-11ea-912c-98f07c2cfa4e.png)

The actual value I get back is a JSON string containing the original 40 byte payload encoded into base64:
![image](https://user-images.githubusercontent.com/7479226/80959899-10258b80-8e08-11ea-8f6b-9a9f6b5a0785.png)

So that seems to indicate that the DAPR SQL component is doing something weird when called by the SDK (and ONLY when called by the SDK - calling the component directly works normally when executed via HTTP, as shown above). Then I realized the SDK is invoking the DAPR API via gRPC so that test above is not representative.

That would seem to indicate that the DAPR SQL component handles HTTP invocation differently than gRPC invocation. So I went and looked into the component source:
https://github.com/dapr/components-contrib/blob/b647397b2c81356b62170e4161aa2393fc7ccf03/state/sqlserver/sqlserver.go#L479

That looks suspicious to me (but I'm no Go coder). But that line looks like the component is converting `Value` into JSON. From the [docs](https://golang.org/pkg/encoding/json/#Marshal):
```
Marshal returns the JSON encoding of v.

Marshal traverses the value v recursively. If an encountered value implements the Marshaler
interface and is not a nil pointer, Marshal calls its MarshalJSON method to produce JSON. If no
MarshalJSON method is present but the value implements encoding.TextMarshaler instead,
Marshal calls its MarshalText method and encodes the result as a JSON string.
```

And I think this is how the payload is getting turned into a JSON string in the database. It would also explain why it works correctly when I invoke the component via HTTP - the Value there gets serialized into JSON properly in that case.

At this point I think this whole ticket belongs in the dapr/components-contrib repo 😕

**Comment by amanbha** [comment]
Thanks @mareklinka  for reporting it and doing the very helpful troubleshooting

**Comment by LMWF** [comment]
This was moved to dapr/components-contrib.
