### ISSUE TITLE
InvokeMethodAsync API is too permissive for DAPR 0.7

### ISSUE THREAD

**Issue by mareklinka** [dapr/dotnet-sdk#302]
I just upgraded my small DAPR playground project from 0.6 to 0.7. After that, my remote invocation calls stopped working with the following exception:
```
Grpc.Core.RpcException: Status(StatusCode=InvalidArgument, Detail="missing HTTP extension field")
   at Dapr.Client.DaprClientGrpc.MakeGrpcCallHandleError[TResponse](Func`2 callFunc, CancellationToken cancellationToken)
   at Dapr.Client.DaprClientGrpc.MakeInvokeRequestAsync(String appId, String methodName, Any data, HTTPExtension httpExtension, CancellationToken cancellationToken)
   at Dapr.Client.DaprClientGrpc.InvokeMethodAsync[TRequest,TResponse](String appId, String methodName, TRequest data, HTTPExtension httpExtension, CancellationToken cancellationToken)
   at DotNetBa.Dapr.Main.Controllers.UserController.Login(LoginModel model, DaprClient dapr, CancellationToken cancellationToken) in C:\Source\Personal\dotnetba-dapr\src\DotNetBa.Dapr.Main\Controllers\UserController.cs:line 44
   at lambda_method(Closure , Object )
   at Microsoft.Extensions.Internal.ObjectMethodExecutorAwaitable.Awaiter.GetResult()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|24_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
```
I traced this to the following DAPR source:
https://github.com/dapr/dapr/blob/41df721108185a399cf6c9096fe414bacb1d8b5d/pkg/channel/http/http_channel.go#L68

This looks like the remote invocation now requires the `HTTPExtension` to be specified. However, the call to `InvokeMethodAsync` marks that parameter as optional with default value of `null` (all overloads):
https://github.com/dapr/dotnet-sdk/blob/44ca6496d8c29e14df2122f6704d24b38a1755a4/src/Dapr.Client/DaprClient.cs#L59-L63

This allows the user to write valid code that cannot work at runtime. I think the API surface should be made stricter to prevent this user error:

``` csharp
// original code - worked in 0.6 and broke in 0.7 (compiles in both)
await dapr.InvokeMethodAsync<LoginRequest, LoginResponse>(Apps.UserService,
                                                                          "login/login",
                                                                          request,
                                                                          cancellationToken: cancellationToken);

// new code - works in 0.7
await dapr.InvokeMethodAsync<LoginRequest, LoginResponse>(Apps.UserService,
                                                                          "login/login",
                                                                          request,
                                                                          new HTTPExtension() { Verb = HTTPVerb.Post },
                                                                          cancellationToken: cancellationToken)

```
This constitutes a breaking change that has not been documented (or maybe I just wasn't able to find it). Therefore I'd like to propose a slight change to the API that would make the `HTTPExtension` parameter required.

**Comment by amanbha** [comment]
@youngbupark Could you please help with it, HTTPExtension is optional as per [proto](https://github.com/dapr/dapr/blob/41df721108185a399cf6c9096fe414bacb1d8b5d/dapr/proto/common/v1/common.proto#L76) Looks like it didn't get set in Dapr when making call to AppChannel and error is returned from [here](https://github.com/dapr/dapr/blob/master/pkg/channel/http/http_channel.go#L72) 

cc @LMWF

**Comment by youngbupark** [comment]
> @youngbupark Could you please help with it, HTTPExtension is optional as per [proto](https://github.com/dapr/dapr/blob/41df721108185a399cf6c9096fe414bacb1d8b5d/dapr/proto/common/v1/common.proto#L76) Looks like it didn't get set in Dapr when making call to AppChannel and error is returned from [here](https://github.com/dapr/dapr/blob/master/pkg/channel/http/http_channel.go#L72)
> 
> cc @LMWF

This is the by-design. As we discussed in the spec review, we decided that it will be **optional** for gRPC AppChannel, but **required** for HTTP appchannel. We need to update comments on proto files--I will do it. So, dotnet-sdk needs to set HTTPExtension to default one if user didn't specify it.

I recalled that we did not have this issue when @LMWF validated the samples.. @LMWF ?

**Comment by youngbupark** [comment]
I have to add the breaking change part to release note as well.

**Comment by amanbha** [comment]
Thanks @youngbupark .  @LMWF In the dotnet api, can we set the verb to POST if user hasn't provided the HTTPExtension?

**Comment by youngbupark** [comment]
I will update release note and add more comments to proto files.

**Comment by youngbupark** [comment]
I have updated release note and create the pr to add additional comment.

**Comment by LMWF** [comment]
> Thanks @youngbupark . @LMWF In the dotnet api, can we use default HTTPExtension and set the verb to POST if user hasn't provided the HTTPExtension?

Yes, that will work if the target app is listening on HTTP, but if it's listening on gRPC, @youngbupark  what happens if you specify HTTPExtensions and set verb to post?  Is it ignored?  If so this will work.

**Comment by youngbupark** [comment]
> > Thanks @youngbupark . @LMWF In the dotnet api, can we use default HTTPExtension and set the verb to POST if user hasn't provided the HTTPExtension?
> 
> Yes, that will work if the target app is listening on HTTP, but if it's listening on gRPC, @youngbupark what happens if you specify HTTPExtensions and set verb to post? Is it ignored? If so this will work.

It should work. gRPC callee user app will be able to get HTTPExtension from InvokeRequest.

**Comment by LMWF** [comment]
Hey @mareklinka thanks for reporting.  We've fixed this in the master branch and will release it with the next release.  It sounds like you have worked around this.  If you need a refreshed nuget earlier please let us know.

**Comment by mareklinka** [comment]
Thanks, @LMWF (and everyone else). I think I'm fine for now, everything works if I just provide the extension myself so no need to rush a newer package for me.
