### ISSUE TITLE
.net core sample (master branch) not working

### ISSUE THREAD

**Issue by RazorscreaM** [dapr/dotnet-sdk#322]
## Ask your question here
Right off the bat, im very new to DAPR, and if i do something wrong please point me in the right direction so to the point:
after installing everything mentioned in the docs when i run the sample i get the following for the 
Actor client:

`dotnet run
Making call using actor proxy to save data.
Unhandled exception. Dapr.Actors.DaprException: error activating actor type DemoActor with id abc: %!s(<nil>)
   at Dapr.Actors.DaprHttpInteractor.SendAsyncHandleUnsuccessfulResponse(Func`1 requestFunc, String relativeUri, String requestId, CancellationToken cancellationToken) in C:\Users\vasile.oleinic\Desktop\Repos\Dapr\Demo\src\Dapr.Actors\DaprHttpInteractor.cs:line 452
   at Dapr.Actors.DaprHttpInteractor.SendAsync(Func`1 requestFunc, String relativeUri, String requestId, CancellationToken cancellationToken) in C:\Users\vasile.oleinic\Desktop\Repos\Dapr\Demo\src\Dapr.Actors\DaprHttpInteractor.cs:line 336
   at Dapr.Actors.DaprHttpInteractor.InvokeActorMethodWithRemotingAsync(ActorMessageSerializersManager serializersManager, IActorRequestMessage remotingRequestRequestMessage, CancellationToken cancellationToken) in C:\Users\vasile.oleinic\Desktop\Repos\Dapr\Demo\src\Dapr.Actors\DaprHttpInteractor.cs:line 164
   at Dapr.Actors.Communication.Client.ActorRemotingClient.InvokeAsync(IActorRequestMessage remotingRequestMessage, String methodName, CancellationToken cancellationToken) in C:\Users\vasile.oleinic\Desktop\Repos\Dapr\Demo\src\Dapr.Actors\Communication\Client\ActorRemotingClient.cs:line 40
   at Dapr.Actors.Client.ActorProxy.InvokeAsync(Int32 interfaceId, Int32 methodId, String methodName, IActorRequestMessageBody requestMsgBodyValue, CancellationToken cancellationToken) in C:\Users\vasile.oleinic\Desktop\Repos\Dapr\Demo\src\Dapr.Actors\Client\ActorProxy.cs:line 206
   at ActorClient.Program.Main(String[] args) in C:\Users\vasile.oleinic\Desktop\Repos\Dapr\Demo\samples\Actor\ActorClient\Program.cs:line 40
   at ActorClient.Program.<Main>(String[] args)
`

And in the dapr logs i see this:

`[94;1m== APP ==       Request starting HTTP/1.1 POST http://127.0.0.1:5000/actors/DemoActor/abc application/json 0
[0m
[94;1m== APP == info: Microsoft.AspNetCore.Routing.EndpointMiddleware[0]
[0m
[94;1m== APP ==       Executing endpoint '405 HTTP Method Not Supported' `

Please could you explain what i do wrong here, or if its some kind of problem how to repair, thx.

**Comment by amanbha** [comment]
master branch is tracking the next release and contains changes for dapr runtime 0.80 to be released next week.
For Dapr runtime 0.7.0, please use samples from release-0.7.0 branch

**Comment by RazorscreaM** [comment]
thx it fixed the issue, closing the ticket.
