### ISSUE TITLE
Unhandled exception. Dapr.Actors.DaprException: error finding address for actor type DemoActor with id abc

### ISSUE THREAD

**Issue by staneee** [dapr/dotnet-sdk#380]
I have the same problem as this #117  , But I don't know how to solve it

# Env

**Operating system:**
```
windows 10 pro x64 
1909
18363.1016
```

**dotnet core sdks:**
```
PS D:\> dotnet --list-sdks
2.2.207 [C:\Program Files\dotnet\sdk]
3.1.102 [C:\Program Files\dotnet\sdk]
3.1.401 [C:\Program Files\dotnet\sdk]
5.0.100-preview.6.20318.15 [C:\Program Files\dotnet\sdk]
```

**dapr installation:**
```
dapr init --slim
```

**dapr version:**
```
PS D:\> dapr --version
CLI version: 0.10.0
Runtime version: 0.10.0
```

---

# Run the Sample Actors Demo

## Run DemoActor:
```
PS D:\dev\ms\dapr_fx\dotnet-sdk\samples\Actor\DemoActor>  dapr run --dapr-http-port 3500 --app-id demo_actor --app-port 5000 dotnet run
Starting Dapr with id demo_actor. HTTP Port: 3500. gRPC Port: 65312
== DAPR == time="2020-08-27T23:22:47.9907943+08:00" level=info msg="starting Dapr Runtime -- version 0.10.0 -- commit 6032dc2" app_id=demo_actor instance=DESKTOP-9FFERBO scope=dapr.runtime type=log ver=0.10.0

== DAPR == time="2020-08-27T23:22:47.9907943+08:00" level=info msg="log level set to: info" app_id=demo_actor instance=DESKTOP-9FFERBO scope=dapr.runtime type=log ver=0.10.0

== DAPR == time="2020-08-27T23:22:47.9917814+08:00" level=info msg="metrics server started on :65313/" app_id=demo_actor instance=DESKTOP-9FFERBO scope=dapr.metrics type=log ver=0.10.0

== DAPR == time="2020-08-27T23:22:47.9967343+08:00" level=warning msg="error loading configuration: CreateFile C:\\Users\\yihan\\.dapr\\config.yaml: The system cannot find the file specified." app_id=demo_actor instance=DESKTOP-9FFERBO scope=dapr.runtime type=log ver=0.10.0

== DAPR == time="2020-08-27T23:22:47.9967343+08:00" level=info msg="loading default configuration" app_id=demo_actor instance=DESKTOP-9FFERBO scope=dapr.runtime type=log ver=0.10.0

== DAPR == time="2020-08-27T23:22:47.9967343+08:00" level=info msg="standalone mode configured" app_id=demo_actor instance=DESKTOP-9FFERBO scope=dapr.runtime type=log ver=0.10.0

== DAPR == time="2020-08-27T23:22:47.9967343+08:00" level=info msg="app id: demo_actor" app_id=demo_actor instance=DESKTOP-9FFERBO scope=dapr.runtime type=log ver=0.10.0

== DAPR == time="2020-08-27T23:22:47.9967343+08:00" level=info msg="mTLS is disabled. Skipping certificate request and tls validation" app_id=demo_actor instance=DESKTOP-9FFERBO scope=dapr.runtime type=log ver=0.10.0

== DAPR == time="2020-08-27T23:22:47.9967343+08:00" level=info msg="application protocol: http. waiting on port 5000.  This will block until the app is listening on that port." app_id=demo_actor instance=DESKTOP-9FFERBO scope=dapr.runtime type=log ver=0.10.0

== APP == Hosting environment: Development

== APP == Content root path: D:\dev\ms\dapr_fx\dotnet-sdk\samples\Actor\DemoActor

== APP == Now listening on: http://localhost:5000

== APP == Application started. Press Ctrl+C to shut down.

== DAPR == time="2020-08-27T23:22:54.615556+08:00" level=info msg="application discovered on port 5000" app_id=demo_actor instance=DESKTOP-9FFERBO scope=dapr.runtime type=log ver=0.10.0

== APP == info: Microsoft.AspNetCore.Hosting.Diagnostics[1]

== APP ==       Request starting HTTP/1.1 GET http://127.0.0.1:5000/dapr/config application/json

== APP == info: Microsoft.AspNetCore.Routing.EndpointMiddleware[0]

== APP ==       Executing endpoint 'dapr/config HTTP: GET'

== APP == info: Microsoft.AspNetCore.Routing.EndpointMiddleware[1]

== APP ==       Executed endpoint 'dapr/config HTTP: GET'

== APP == info: Microsoft.AspNetCore.Hosting.Diagnostics[2]

== APP ==       Request finished in 52.7697ms 200 application/json

== DAPR == time="2020-08-27T23:22:54.7135611+08:00" level=info msg="application configuration loaded" app_id=demo_actor instance=DESKTOP-9FFERBO scope=dapr.runtime type=log ver=0.10.0

== DAPR == time="2020-08-27T23:22:54.7145583+08:00" level=warning msg="either no actor state store or multiple actor state stores are specified in the configuration, actor stores specified: 0" app_id=demo_actor instance=DESKTOP-9FFERBO scope=dapr.runtime type=log ver=0.10.0

== DAPR == time="2020-08-27T23:22:54.7660452+08:00" level=info msg="local service entry announced: demo_actor -> 192.168.119.4:65318" app_id=demo_actor instance=DESKTOP-9FFERBO scope=dapr.contrib type=log ver=0.10.0

== DAPR == time="2020-08-27T23:22:54.7660452+08:00" level=info msg="Initialized name resolution to standalone" app_id=demo_actor instance=DESKTOP-9FFERBO scope=dapr.runtime type=log ver=0.10.0

== DAPR == time="2020-08-27T23:22:54.7660452+08:00" level=warning msg="actors: state store must be present to initialize the actor runtime" app_id=demo_actor instance=DESKTOP-9FFERBO scope=dapr.runtime.actor type=log ver=0.10.0

== DAPR == time="2020-08-27T23:22:54.7665556+08:00" level=warning msg="failed to init actors: state store does not support transactions which actors require to save state - please see https://github.com/dapr/docs" app_id=demo_actor instance=DESKTOP-9FFERBO scope=dapr.runtime type=log ver=0.10.0

== DAPR == time="2020-08-27T23:22:54.7665556+08:00" level=info msg="enabled gRPC tracing middleware" app_id=demo_actor instance=DESKTOP-9FFERBO scope=dapr.runtime.grpc.api type=log ver=0.10.0

== DAPR == time="2020-08-27T23:22:54.7665556+08:00" level=info msg="enabled gRPC metrics middleware" app_id=demo_actor instance=DESKTOP-9FFERBO scope=dapr.runtime.grpc.api type=log ver=0.10.0

== DAPR == time="2020-08-27T23:22:54.7665556+08:00" level=info msg="API gRPC server is running on port 65312" app_id=demo_actor instance=DESKTOP-9FFERBO scope=dapr.runtime type=log ver=0.10.0

== DAPR == time="2020-08-27T23:22:54.7665556+08:00" level=info msg="enabled gRPC tracing middleware" app_id=demo_actor instance=DESKTOP-9FFERBO scope=dapr.runtime.grpc.internal type=log ver=0.10.0

== DAPR == time="2020-08-27T23:22:54.7665556+08:00" level=info msg="enabled gRPC metrics middleware" app_id=demo_actor instance=DESKTOP-9FFERBO scope=dapr.runtime.grpc.internal type=log ver=0.10.0

== DAPR == time="2020-08-27T23:22:54.7665556+08:00" level=info msg="internal gRPC server is running on port 65318" app_id=demo_actor instance=DESKTOP-9FFERBO scope=dapr.runtime type=log ver=0.10.0

== DAPR == time="2020-08-27T23:22:54.7665556+08:00" level=info msg="enabled cors http middleware" app_id=demo_actor instance=DESKTOP-9FFERBO scope=dapr.runtime.http type=log ver=0.10.0

== DAPR == time="2020-08-27T23:22:54.7665556+08:00" level=info msg="enabled metrics http middleware" app_id=demo_actor instance=DESKTOP-9FFERBO scope=dapr.runtime.http type=log ver=0.10.0

== DAPR == time="2020-08-27T23:22:54.7665556+08:00" level=info msg="enabled tracing http middleware" app_id=demo_actor instance=DESKTOP-9FFERBO scope=dapr.runtime.http type=log ver=0.10.0

== DAPR == time="2020-08-27T23:22:54.7665556+08:00" level=info msg="http server is running on port 3500" app_id=demo_actor instance=DESKTOP-9FFERBO scope=dapr.runtime type=log ver=0.10.0

== DAPR == time="2020-08-27T23:22:54.7665556+08:00" level=info msg="dapr initialized. Status: Running. Init Elapsed 6769.8213000000005ms" app_id=demo_actor instance=DESKTOP-9FFERBO scope=dapr.runtime type=log ver=0.10.0

Updating metadata for app command: dotnet run
You're up and running! Both Dapr and your app logs will appear here.

```

## Run ActorClient:
```
PS D:\dev\ms\dapr_fx\dotnet-sdk\samples\Actor\ActorClient> dotnet run
Making call using actor proxy to save data.
Unhandled exception. Dapr.Actors.DaprException: error finding address for actor type DemoActor with id abc
   at Dapr.Actors.DaprHttpInteractor.SendAsyncHandleUnsuccessfulResponse(Func`1 requestFunc, String relativeUri, CancellationToken cancellationToken)
   at Dapr.Actors.DaprHttpInteractor.SendAsync(Func`1 requestFunc, String relativeUri, CancellationToken cancellationToken)
   at Dapr.Actors.DaprHttpInteractor.InvokeActorMethodWithRemotingAsync(ActorMessageSerializersManager serializersManager, IActorRequestMessage remotingRequestRequestMessage, CancellationToken cancellationToken)
   at Dapr.Actors.Communication.Client.ActorRemotingClient.InvokeAsync(IActorRequestMessage remotingRequestMessage, String methodName, CancellationToken cancellationToken)
   at Dapr.Actors.Client.ActorProxy.InvokeAsync(Int32 interfaceId, Int32 methodId, String methodName, IActorRequestMessageBody requestMsgBodyValue, CancellationToken cancellationToken)
   at ActorClient.Program.Main(String[] args) in D:\dev\ms\dapr_fx\dotnet-sdk\samples\Actor\ActorClient\Program.cs:line 42
   at ActorClient.Program.<Main>(String[] args)
```

## Dashboard

**version:**
```
PS D:\> dapr dashboard -v
0.2.0
```

**run:**
```
PS D:\> dapr dashboard
Dapr Dashboard running on http://localhost:8080
```

**views:**
![image](https://user-images.githubusercontent.com/26987099/91462437-bec07100-e8bc-11ea-8166-cf4ccda71577.png)

![image](https://user-images.githubusercontent.com/26987099/91462464-c718ac00-e8bc-11ea-8dc3-e3bd603f2af6.png)

![image](https://user-images.githubusercontent.com/26987099/91462492-cf70e700-e8bc-11ea-86fb-941412521d6f.png)

**Comment by amanbha** [comment]
@staneee I se that you have used dapr init --slim which sets up minimal dapr dev environment and needs user to run placement service and other components. Could you try with dapr init. I am closing this for now, feel free to reopen if it still repros with dapr init.

**Comment by staneee** [comment]
@amanbha How should I configure to run and placement services or other components when I use `dapr init --slim`

**Comment by amanbha** [comment]
Please here https://github.com/dapr/cli#slim-init

For configuring components (eg. redis store, please see https://github.com/dapr/docs/blob/master/howto/setup-state-store/setup-redis.md). 

For running placement:
Run placement as: %userprofile%\.dapr\bin\placement.exe --port 6050

Then run the app using cli, pass the path to components folder using `--components-path` flag.
If you run placement on other than the default port 6050, pass it using the `--placement-host-address` flag as localhost:port
