### ISSUE TITLE
Faced issue Dapr.Actors.DaprException: context deadline exceeded while deploying in local kubernetes cluster

### ISSUE THREAD

**Issue by amitHansda** [dapr/dotnet-sdk#409]
## Expected Behavior
I made a dapr application which creates an actor service. On Self Hosted mode it is working fine,so I tried to deploy the same in local k8s cluster. However in kubernetes cluster I am facing this exception *Dapr.Actors.DaprException: context deadline exceeded*
**basically**, whenever it attempts to do anything with actor instance, it is throwing the same exception.

I also verified whether redis StateStore has been configured correctly or not. By deploying another application which performs get/set operation in the state store. I'm facing no issue there.

## Actual Behavior
This is the detailed log from the container inside the pod
```

   at Dapr.Actors.DaprHttpInteractor.SendAsyncHandleUnsuccessfulResponse(Func`1 requestFunc, String relativeUri, CancellationToken cancellationToken)
   at Dapr.Actors.DaprHttpInteractor.SendAsync(Func`1 requestFunc, String relativeUri, CancellationToken cancellationToken)
   at Dapr.Actors.DaprHttpInteractor.InvokeActorMethodWithRemotingAsync(ActorMessageSerializersManager serializersManager, IActorRequestMessage remotingRequestRequestMessage, CancellationToken cancellationToken)

   at Dapr.Actors.Communication.Client.ActorRemotingClient.InvokeAsync(IActorRequestMessage remotingRequestMessage, String methodName, CancellationToken cancellationToken)
   at Dapr.Actors.Client.ActorProxy.InvokeAsync(Int32 interfaceId, Int32 methodId, String methodName, IActorRequestMessageBody requestMsgBodyValue, CancellationToken cancellationToken)
   at Dapr.Actors.Client.ActorProxy.ContinueWithResult[TRetval](Int32 interfaceId, Int32 methodId, Task`1 task)
   at MyActor.Service.WebClient.Controllers.TestController.SetDataAsync(String actorId, MyData model) in /source/MyActor.Service.WebClient/Controllers/TestController.cs:line 28
```

## Steps to Reproduce the Problem
This is the state store component I am using
```
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: statestore
  namespace: default
spec:
  type: state.redis
  metadata:
  - name: redisHost
    value: redis-master.default.svc.cluster.local:6379
  - name: redisPassword
    secretKeyRef:
      name: redis
      key: redis-password
  - name: actorStateStore
    value: "true"
```

**Dapr CLI and Runtime Version**
```
CLI version: 0.11.0
Runtime version: 0.11.0
```

**Screenshots from Dapr Dashboard**
![image](https://user-images.githubusercontent.com/18718920/94807860-dc2db100-040d-11eb-848f-0a5790e09345.png)

![image](https://user-images.githubusercontent.com/18718920/94807694-a5579b00-040d-11eb-847c-6a2de88c7991.png)

**Comment by vinayada1** [comment]
Questions:-
1. Was this working with previous releases?
2. Could you also add logs from daprd?

**Comment by amitHansda** [comment]
> Questions:-
> 
> 1. Was this working with previous releases?
> 2. Could you also add logs from daprd?

1. This is my first attempt at deploying actors in k8s. Didn't work with previous version. Are you suggesting bring down local l8s dapr services, and reinitiate dapr with earlier version?
2. **Here is the logs for daprd from Client Application**
```
time="2020-10-02T04:31:56.898482423Z" level=info msg="starting Dapr Runtime -- version 0.11.0 -- commit 71f9fb5" app_id=daprexample-myactorwebclient instance=daprexample-myactorwebclient-769fcdbff8-jv6zz scope=dapr.runtime type=log ver=0.11.0
time="2020-10-02T04:31:56.898558923Z" level=info msg="log level set to: info" app_id=daprexample-myactorwebclient instance=daprexample-myactorwebclient-769fcdbff8-jv6zz scope=dapr.runtime type=log ver=0.11.0
time="2020-10-02T04:31:56.898753323Z" level=info msg="metrics server started on :9090/" app_id=daprexample-myactorwebclient instance=daprexample-myactorwebclient-769fcdbff8-jv6zz scope=dapr.metrics type=log ver=0.11.0
time="2020-10-02T04:31:56.898933723Z" level=info msg="loading default configuration" app_id=daprexample-myactorwebclient instance=daprexample-myactorwebclient-769fcdbff8-jv6zz scope=dapr.runtime type=log ver=0.11.0
time="2020-10-02T04:31:56.899157423Z" level=info msg="kubernetes mode configured" app_id=daprexample-myactorwebclient instance=daprexample-myactorwebclient-769fcdbff8-jv6zz scope=dapr.runtime type=log ver=0.11.0
time="2020-10-02T04:31:56.899170023Z" level=info msg="app id: daprexample-myactorwebclient" app_id=daprexample-myactorwebclient instance=daprexample-myactorwebclient-769fcdbff8-jv6zz scope=dapr.runtime type=log ver=0.11.0
time="2020-10-02T04:31:56.899182223Z" level=info msg="mTLS enabled. creating sidecar authenticator" app_id=daprexample-myactorwebclient instance=daprexample-myactorwebclient-769fcdbff8-jv6zz scope=dapr.runtime type=log ver=0.11.0
time="2020-10-02T04:31:56.899434323Z" level=info msg="trust anchors and cert chain extracted successfully" app_id=daprexample-myactorwebclient instance=daprexample-myactorwebclient-769fcdbff8-jv6zz scope=dapr.runtime.security type=log ver=0.11.0
time="2020-10-02T04:31:56.899467123Z" level=info msg="authenticator created" app_id=daprexample-myactorwebclient instance=daprexample-myactorwebclient-769fcdbff8-jv6zz scope=dapr.runtime type=log ver=0.11.0
time="2020-10-02T04:31:56.908893123Z" level=info msg="application protocol: http. waiting on port 80.  This will block until the app is listening on that port." app_id=daprexample-myactorwebclient instance=daprexample-myactorwebclient-769fcdbff8-jv6zz scope=dapr.runtime type=log ver=0.11.0
time="2020-10-02T04:31:57.340674222Z" level=info msg="application discovered on port 80" app_id=daprexample-myactorwebclient instance=daprexample-myactorwebclient-769fcdbff8-jv6zz scope=dapr.runtime type=log ver=0.11.0
time="2020-10-02T04:31:58.56289872Z" level=info msg="application configuration loaded" app_id=daprexample-myactorwebclient instance=daprexample-myactorwebclient-769fcdbff8-jv6zz scope=dapr.runtime type=log ver=0.11.0
time="2020-10-02T04:31:58.56300122Z" level=info msg="Initialized name resolution to kubernetes" app_id=daprexample-myactorwebclient instance=daprexample-myactorwebclient-769fcdbff8-jv6zz scope=dapr.runtime type=log ver=0.11.0
time="2020-10-02T04:31:59.827292118Z" level=info msg="component loaded. name: kubernetes, type: secretstores.kubernetes" app_id=daprexample-myactorwebclient instance=daprexample-myactorwebclient-769fcdbff8-jv6zz scope=dapr.runtime type=log ver=0.11.0
time="2020-10-02T04:32:00.945093015Z" level=info msg="component loaded. name: pubsub, type: pubsub.redis" app_id=daprexample-myactorwebclient instance=daprexample-myactorwebclient-769fcdbff8-jv6zz scope=dapr.runtime type=log ver=0.11.0
time="2020-10-02T04:32:00.945504015Z" level=info msg="waiting for all outstanding components to be processed" app_id=daprexample-myactorwebclient instance=daprexample-myactorwebclient-769fcdbff8-jv6zz scope=dapr.runtime type=log ver=0.11.0
time="2020-10-02T04:32:01.036567015Z" level=info msg="component loaded. name: statestore, type: state.redis" app_id=daprexample-myactorwebclient instance=daprexample-myactorwebclient-769fcdbff8-jv6zz scope=dapr.runtime type=log ver=0.11.0
time="2020-10-02T04:32:01.036680815Z" level=info msg="all outstanding components processed" app_id=daprexample-myactorwebclient instance=daprexample-myactorwebclient-769fcdbff8-jv6zz scope=dapr.runtime type=log ver=0.11.0
time="2020-10-02T04:32:01.036869515Z" level=info msg="actor runtime started. actor idle timeout: 1h0m0s. actor scan interval: 30s" app_id=daprexample-myactorwebclient instance=daprexample-myactorwebclient-769fcdbff8-jv6zz scope=dapr.runtime.actor type=log ver=0.11.0
time="2020-10-02T04:32:01.037150215Z" level=info msg="enabled gRPC tracing middleware" app_id=daprexample-myactorwebclient instance=daprexample-myactorwebclient-769fcdbff8-jv6zz scope=dapr.runtime.grpc.api type=log ver=0.11.0
time="2020-10-02T04:32:01.037211715Z" level=info msg="enabled gRPC metrics middleware" app_id=daprexample-myactorwebclient instance=daprexample-myactorwebclient-769fcdbff8-jv6zz scope=dapr.runtime.grpc.api type=log ver=0.11.0
time="2020-10-02T04:32:01.037330215Z" level=info msg="starting connection attempt to placement service: dapr-placement.dapr-system.svc.cluster.local:80" app_id=daprexample-myactorwebclient instance=daprexample-myactorwebclient-769fcdbff8-jv6zz scope=dapr.runtime.actor type=log ver=0.11.0
time="2020-10-02T04:32:01.196212514Z" level=info msg="API gRPC server is running on port 50001" app_id=daprexample-myactorwebclient instance=daprexample-myactorwebclient-769fcdbff8-jv6zz scope=dapr.runtime type=log ver=0.11.0
time="2020-10-02T04:32:01.196479314Z" level=info msg="enabled gRPC tracing middleware" app_id=daprexample-myactorwebclient instance=daprexample-myactorwebclient-769fcdbff8-jv6zz scope=dapr.runtime.grpc.internal type=log ver=0.11.0
time="2020-10-02T04:32:01.196533514Z" level=info msg="enabled gRPC metrics middleware" app_id=daprexample-myactorwebclient instance=daprexample-myactorwebclient-769fcdbff8-jv6zz scope=dapr.runtime.grpc.internal type=log ver=0.11.0
time="2020-10-02T04:32:01.196552814Z" level=info msg="sending workload csr request to sentry" app_id=daprexample-myactorwebclient instance=daprexample-myactorwebclient-769fcdbff8-jv6zz scope=dapr.runtime.grpc.internal type=log ver=0.11.0
time="2020-10-02T04:32:03.260011409Z" level=info msg="established connection to placement service at dapr-placement.dapr-system.svc.cluster.local:80" app_id=daprexample-myactorwebclient instance=daprexample-myactorwebclient-769fcdbff8-jv6zz scope=dapr.runtime.actor type=log ver=0.11.0
time="2020-10-02T04:32:03.315012109Z" level=info msg="placement order received: lock" app_id=daprexample-myactorwebclient instance=daprexample-myactorwebclient-769fcdbff8-jv6zz scope=dapr.runtime.actor type=log ver=0.11.0
time="2020-10-02T04:32:03.318578709Z" level=info msg="placement order received: update" app_id=daprexample-myactorwebclient instance=daprexample-myactorwebclient-769fcdbff8-jv6zz scope=dapr.runtime.actor type=log ver=0.11.0
time="2020-10-02T04:32:03.318646309Z" level=info msg="placement tables updated, version: 0" app_id=daprexample-myactorwebclient instance=daprexample-myactorwebclient-769fcdbff8-jv6zz scope=dapr.runtime.actor type=log ver=0.11.0
time="2020-10-02T04:32:03.318678009Z" level=info msg="placement order received: unlock" app_id=daprexample-myactorwebclient instance=daprexample-myactorwebclient-769fcdbff8-jv6zz scope=dapr.runtime.actor type=log ver=0.11.0
time="2020-10-02T04:32:03.723057808Z" level=info msg="certificate signed successfully" app_id=daprexample-myactorwebclient instance=daprexample-myactorwebclient-769fcdbff8-jv6zz scope=dapr.runtime.grpc.internal type=log ver=0.11.0
time="2020-10-02T04:32:04.008095707Z" level=info msg="internal gRPC server is running on port 50002" app_id=daprexample-myactorwebclient instance=daprexample-myactorwebclient-769fcdbff8-jv6zz scope=dapr.runtime type=log ver=0.11.0
time="2020-10-02T04:32:03.997224607Z" level=info msg="starting workload cert expiry watcher. current cert expires on: 2020-10-03 04:47:03 +0000 UTC" app_id=daprexample-myactorwebclient instance=daprexample-myactorwebclient-769fcdbff8-jv6zz scope=dapr.runtime.grpc.internal type=log ver=0.11.0
time="2020-10-02T04:32:04.075475607Z" level=info msg="enabled cors http middleware" app_id=daprexample-myactorwebclient instance=daprexample-myactorwebclient-769fcdbff8-jv6zz scope=dapr.runtime.http type=log ver=0.11.0
time="2020-10-02T04:32:04.075545907Z" level=info msg="enabled metrics http middleware" app_id=daprexample-myactorwebclient instance=daprexample-myactorwebclient-769fcdbff8-jv6zz scope=dapr.runtime.http type=log ver=0.11.0
time="2020-10-02T04:32:04.075561307Z" level=info msg="enabled tracing http middleware" app_id=daprexample-myactorwebclient instance=daprexample-myactorwebclient-769fcdbff8-jv6zz scope=dapr.runtime.http type=log ver=0.11.0
time="2020-10-02T04:32:04.075729107Z" level=info msg="http server is running on port 3500" app_id=daprexample-myactorwebclient instance=daprexample-myactorwebclient-769fcdbff8-jv6zz scope=dapr.runtime type=log ver=0.11.0
time="2020-10-02T04:32:04.075752807Z" level=info msg="dapr initialized. Status: Running. Init Elapsed 7176.602184ms" app_id=daprexample-myactorwebclient instance=daprexample-myactorwebclient-769fcdbff8-jv6zz scope=dapr.runtime type=log ver=0.11.0
time="2020-10-02T04:32:28.967169639Z" level=info msg="placement order received: lock" app_id=daprexample-myactorwebclient instance=daprexample-myactorwebclient-769fcdbff8-jv6zz scope=dapr.runtime.actor type=log ver=0.11.0
time="2020-10-02T04:32:28.967444339Z" level=info msg="placement order received: update" app_id=daprexample-myactorwebclient instance=daprexample-myactorwebclient-769fcdbff8-jv6zz scope=dapr.runtime.actor type=log ver=0.11.0
time="2020-10-02T04:32:28.967503139Z" level=info msg="placement tables updated, version: 1" app_id=daprexample-myactorwebclient instance=daprexample-myactorwebclient-769fcdbff8-jv6zz scope=dapr.runtime.actor type=log ver=0.11.0
time="2020-10-02T04:32:28.967545339Z" level=info msg="placement order received: unlock" app_id=daprexample-myactorwebclient instance=daprexample-myactorwebclient-769fcdbff8-jv6zz scope=dapr.runtime.actor type=log ver=0.11.0
```

**Comment by amitHansda** [comment]
@vinayada1 Closing this one. This morning updated cluster to 0.11 instead of 0.11-rc-1
