### ISSUE TITLE
Dapr Actors fails to serialize exceptions

### ISSUE THREAD

**Issue by rynowak** [dapr/dotnet-sdk#445]
## Expected Behavior

Dapr Actors (as a client) tries to rehydrate exceptions thrown by the server on the client side. This a really dangerous behavior whenever an untrusted code path is involved. See #414 

The good news is that it's broken. 

This feature should probably be removed, but in the event that it's not, this issue exists to document that it doesn't work.

## Actual Behavior

Dapr throws an exception trying to read the exception.

```txt
[2020-10-19T22:04:06.850Z] Error: Dapr.Actors.Communication.ServiceException: Failed to deserialize and get remote exception  System.Runtime.Serialization.SerializationException: The constructor to deserialize an object of type 'Dapr.Actors.ActorMethodInvocationException' was not found.
 ---> System.Runtime.Serialization.SerializationException: The constructor to deserialize an object of type 'Dapr.Actors.ActorMethodInvocationException' was not found.
   at System.Runtime.Serialization.ObjectManager.GetDeserializationConstructor(Type t)
   at System.Runtime.Serialization.ObjectManager.CompleteISerializableObject(Object obj, SerializationInfo info, StreamingContext context)
   --- End of inner exception stack trace ---
   at System.Runtime.Serialization.ObjectManager.CompleteISerializableObject(Object obj, SerializationInfo info, StreamingContext context)
   at System.Runtime.Serialization.ObjectManager.FixupSpecialObject(ObjectHolder holder)
   at System.Runtime.Serialization.ObjectManager.DoFixups()
   at System.Runtime.Serialization.Formatters.Binary.ObjectReader.Deserialize(BinaryParser serParser, Boolean fCheck)
   at System.Runtime.Serialization.Formatters.Binary.BinaryFormatter.Deserialize(Stream serializationStream, Boolean check)
   at System.Runtime.Serialization.Formatters.Binary.BinaryFormatter.Deserialize(Stream serializationStream)
   at Dapr.Actors.Communication.RemoteException.TryDeserializeException(Stream data, Exception& result)
   at Dapr.Actors.DaprHttpInteractor.InvokeActorMethodWithRemotingAsync(ActorMessageSerializersManager serializersManager, IActorRequestMessage remotingRequestRequestMessage, CancellationToken cancellationToken)
   at Dapr.Actors.Communication.Client.ActorRemotingClient.InvokeAsync(IActorRequestMessage remotingRequestMessage, String methodName, CancellationToken cancellationToken)
   at Dapr.Actors.Client.ActorProxy.InvokeAsync(Int32 interfaceId, Int32 methodId, String methodName, IActorRequestMessageBody requestMsgBodyValue, CancellationToken cancellationToken)
   at Frontend.Shared.JoinGameScreen.TryJoinGameAsync() in /Users/ryan/github.com/rynowak/rock-paper-actors/src/Frontend/Shared/JoinGameScreen.razor:line 66
```

## Steps to Reproduce the Problem

Modify the Dapr Actors server sample project to throw an exception.

Run the sample and you'll see an exception like this.

note: you are not seeing the original exception thrown by the server - this is an exception thrown by the client because it fails to read the data.

## Release Note

RELEASE NOTE:

**Comment by malotho** [comment]
Should I pick this up?

**Comment by galvesribeiro** [comment]
Interesting... What happens if the actor wants to throw an exception intentionally so the client can try/catch the actor method call?

In other actor frameworks like Orleans/SF/Akka.Net, the exception is transparently bubbled up to the client so they can handle it. 

If I understood correctly you want to remove the exception to going up to the client but, what happens if an exception is thrown? Would it just be swallowed by the server runtime and logged? What can the client expect?

**Comment by malotho** [comment]
@rynowak please correct me if I am wrong..
We're not removing the exception from bubbling up to the client, we're simply removing/changing the way the serialisation happens for exceptions. We're removing the binaryfomatter.

**Comment by rynowak** [comment]
> We're not removing the exception from bubbling up to the client, we're simply removing/changing the way the serialisation happens for exceptions. We're removing the binaryfomatter.

That's the proposal here. 

This is a problem that *every* actor framework needs to reckon with - specifically that BinaryFormatter will be off by default in .NET 5.0 for web probjects.

BinaryFormatter is a vulnerability when used with untrusted input - `Type.GetType` is a vulnerability when used with untrusted input. Any solution that tries to serialize and deserialize arbitrary types has to have a list of "known safe" types. With `try/catch` something like that is not built-in.

**Comment by galvesribeiro** [comment]
Yes, I agree. But, that is why all actor frameworks out there are not supposed to be exposed for public consumption but instead, being hosted in a safe network and receive requests from trusted clients that have access to it.

But now with your answer I got more confuse... How are the caller (a trusted client) supposed to try/catch an exception if the way to set fields on `Exception` types are being removed? 

Sorry, I'm genuinely confuse.

**Comment by codeputer** [comment]
I’m may be a off-track here, but serialization of Actor state to JSON is not that easy IMO.  The JSON serialization/deserialization means that you MUST have a public constructor, and all properties must be public read/write.  As I like write defensible classes, these restrictions means that I’m constantly moving data between class that I use for persistence, and class that I use for application purposes when it comes to saving state.

I’m sure this is a little unorthodox, but I use a special “wrapping” class that has a few properties which allows for serialization to JSON, but rehydrates using the Binary Formatter… I binary serialize, encode to UTF and stuff the whole thing into a property ZygoteBytes (BTW – this was largely an experiment, but it so easy to save and restore the state of the actor!)


[Serializable]
  public class ZygoteSerializationWrapper
  {


    /// <summary>
    /// Determines how the class, which is being transported, has been serialized into bytes
    /// </summary>
    public string SerializorUsed { get; set; }

    /// <summary>
    /// The name of the type being serialized
    /// </summary>
    public string TypeSerialized { get; set; }

    /// <summary>
    /// The fully qualified name of the Type, including the assembly name
    /// (required for dynamic load of dll which contains the type)
    /// </summary>
    public string FullQualifiedAssembyName { get; set; }

    /// <summary>
    /// Security Signature should the ZgoteBytes need encryption
    /// </summary>
    public string Signature { get; set; }

    /// <summary>
    /// Version of the type being serialized
    /// </summary>
    public string Version { get; set; } = "1";

    /// <summary>
    /// Use the ZgoteWrapper to create this class, and serialize type into bytes
    /// using a binary serializer
    /// </summary>
    public byte[] ZygoteBytes { get; set;  }
  }
}

BTW – I named it Zygote because it is as simple as it gets for serialization

**Comment by vinayada1** [comment]
removed binary formatter
