### ISSUE TITLE
Some actors unit tests have a timing bug and fail undeterministically

### ISSUE THREAD

**Issue by rynowak** [dapr/dotnet-sdk#573]
## Description

We see test failures like:

```
Failed Dapr.Actors.Test.DaprHttpInteractorTest.GetState_ValidateRequest [176 ms]
  Error Message:
   Expected handler.Requests.TryDequeue(out var entry) to be true, but found False.
  Stack Trace:
     at FluentAssertions.Execution.XUnit2TestFramework.Throw(String message)
   at FluentAssertions.Execution.TestFrameworkProvider.Throw(String message)
   at FluentAssertions.Execution.DefaultAssertionStrategy.HandleFailure(String message)
   at FluentAssertions.Execution.AssertionScope.FailWith(Func`1 failReasonFunc)
   at FluentAssertions.Execution.AssertionScope.FailWith(Func`1 failReasonFunc)
   at FluentAssertions.Execution.AssertionScope.FailWith(String message, Object[] args)
   at FluentAssertions.Primitives.BooleanAssertions.BeTrue(String because, Object[] becauseArgs)
   at Dapr.Actors.Test.DaprHttpInteractorTest.GetState_ValidateRequest() in /Users/ryan/github.com/dapr/dotnet-sdk/test/Dapr.Actors.Test/DaprHttpInteractorTest.cs:line 75
```

This is likely the case because methods like `GetStateAsync` yield control before they have enqueued the HTTP message. We should change the pattern in tests to be more robust.

**Comment by rynowak** [comment]
Fixed by #589
