### ISSUE TITLE
Actors service did not work which was very similary to dotnet-sdk\examples\Actor\DemoActor

### ISSUE THREAD

**Issue by mjtansin** [dapr/dotnet-sdk#660]
I made a project referened by examples\Actor\DemoActor, and run by cmd "dapr run... ", the logs **didn't show errors,** but some actions about actors didn't go finished when I compared to DemoActor's logs.
The difference between my project to DemoActor was that I made asp.net core project by vs2019, and dapar packages were installed by nuget package manager

//1----------------------------------------------------------------------------------------------
The Dependencies of project like this
--Frameworks
                   |-----Microsoft.AspNetCore.App
                   |-----Microsoft.NetCore.App
--Packages
                  |-----Dapr.Actors(1.1.0)
                  |-----Dapr.Actors.AspNetCore(1.1.0)
                  |-----Dapr.AspNetCore(1.1.0)
                  |-----Dapr.Extensions.Congiguration(1.1.0)

And the logs :
dapr run --dapr-http-port 3500 --app-id demo_actor --app-port 5000 dotnet run
Starting Dapr with id demo_actor. HTTP Port: 3500. gRPC Port: 59534
time="2021-04-20T11:11:10.5597242+08:00" level=info msg="starting Dapr Runtime -- version 1.0.1 -- commit 45bc40d" app_id=demo_actor instance=tanxin-3490 scope=dapr.runtime type=log ver=1.0.1
time="2021-04-20T11:11:10.5597242+08:00" level=info msg="log level set to: info" app_id=demo_actor instance=tanxin-3490 scope=dapr.runtime type=log ver=1.0.1
time="2021-04-20T11:11:10.5607233+08:00" level=info msg="metrics server started on :59535/" app_id=demo_actor instance=tanxin-3490 scope=dapr.metrics type=log ver=1.0.1
time="2021-04-20T11:11:10.5687253+08:00" level=info msg="standalone mode configured" app_id=demo_actor instance=tanxin-3490 scope=dapr.runtime type=log ver=1.0.1
time="2021-04-20T11:11:10.5707251+08:00" level=info msg="app id: demo_actor" app_id=demo_actor instance=tanxin-3490 scope=dapr.runtime type=log ver=1.0.1
time="2021-04-20T11:11:10.5737232+08:00" level=info msg="mTLS is disabled. Skipping certificate request and tls validation" app_id=demo_actor instance=tanxin-3490 scope=dapr.runtime type=log ver=1.0.1
time="2021-04-20T11:11:10.5877239+08:00" level=info msg="local service entry announced: demo_actor -> 10.128.0.78:59539" app_id=demo_actor instance=tanxin-3490 scope=dapr.contrib type=log ver=1.0.1
time="2021-04-20T11:11:10.5877239+08:00" level=info msg="Initialized name resolution to standalone" app_id=demo_actor instance=tanxin-3490 scope=dapr.runtime type=log ver=1.0.1
time="2021-04-20T11:11:10.5940988+08:00" level=info msg="component loaded. name: pubsub, type: pubsub.redis/" app_id=demo_actor instance=tanxin-3490 scope=dapr.runtime type=log ver=1.0.1
time="2021-04-20T11:11:10.594603+08:00" level=info msg="waiting for all outstanding components to be processed" app_id=demo_actor instance=tanxin-3490 scope=dapr.runtime type=log ver=1.0.1
time="2021-04-20T11:11:10.6025541+08:00" level=info msg="component loaded. name: statestore, type: state.redis/" app_id=demo_actor instance=tanxin-3490 scope=dapr.runtime type=log ver=1.0.1
time="2021-04-20T11:11:10.6031069+08:00" level=info msg="all outstanding components processed" app_id=demo_actor instance=tanxin-3490 scope=dapr.runtime type=log ver=1.0.1
time="2021-04-20T11:11:10.6036985+08:00" level=info msg="enabled gRPC tracing middleware" app_id=demo_actor instance=tanxin-3490 scope=dapr.runtime.grpc.api type=log ver=1.0.1
time="2021-04-20T11:11:10.6053481+08:00" level=info msg="enabled gRPC metrics middleware" app_id=demo_actor instance=tanxin-3490 scope=dapr.runtime.grpc.api type=log ver=1.0.1
time="2021-04-20T11:11:10.605903+08:00" level=info msg="API gRPC server is running on port 59534" app_id=demo_actor instance=tanxin-3490 scope=dapr.runtime type=log ver=1.0.1
time="2021-04-20T11:11:10.606465+08:00" level=info msg="enabled metrics http middleware" app_id=demo_actor instance=tanxin-3490 scope=dapr.runtime.http type=log ver=1.0.1
time="2021-04-20T11:11:10.6070302+08:00" level=info msg="enabled tracing http middleware" app_id=demo_actor instance=tanxin-3490 scope=dapr.runtime.http type=log ver=1.0.1
time="2021-04-20T11:11:10.607635+08:00" level=info msg="http server is running on port 3500" app_id=demo_actor instance=tanxin-3490 scope=dapr.runtime type=log ver=1.0.1
time="2021-04-20T11:11:10.6091753+08:00" level=info msg="The request body size parameter is: 4" app_id=demo_actor instance=tanxin-3490 scope=dapr.runtime type=log ver=1.0.1
time="2021-04-20T11:11:10.6097248+08:00" level=info msg="enabled gRPC tracing middleware" app_id=demo_actor instance=tanxin-3490 scope=dapr.runtime.grpc.internal type=log ver=1.0.1
time="2021-04-20T11:11:10.6113617+08:00" level=info msg="enabled gRPC metrics middleware" app_id=demo_actor instance=tanxin-3490 scope=dapr.runtime.grpc.internal type=log ver=1.0.1
time="2021-04-20T11:11:10.6122825+08:00" level=info msg="internal gRPC server is running on port 59539" app_id=demo_actor instance=tanxin-3490 scope=dapr.runtime type=log ver=1.0.1
time="2021-04-20T11:11:10.6122825+08:00" level=info msg="application protocol: http. waiting on port 5000.  This will block until the app is listening on that port." app_id=demo_actor instance=tanxin-3490 scope=dapr.runtime type=log ver=1.0.1
Updating metadata for app command: dotnet run
**You're up and running! Both Dapr and your app logs will appear here.**

== APP == info: Microsoft.Hosting.Lifetime[0]

== APP ==       Now listening on: http://localhost:5000

== APP == info: Microsoft.Hosting.Lifetime[0]

== APP ==       Application started. Press Ctrl+C to shut down.

== APP == info: Microsoft.Hosting.Lifetime[0]

== APP ==       Hosting environment: Development

== APP == info: Microsoft.Hosting.Lifetime[0]

== APP ==       Content root path: xxxxx\xxxxx

time="2021-04-20T11:11:13.9248624+08:00" level=info msg="application discovered on port 5000" app_id=demo_actor instance=tanxin-3490 scope=dapr.runtime type=log ver=1.0.1
time="2021-04-20T11:11:14.0044456+08:00" level=info msg="application configuration loaded" app_id=demo_actor instance=tanxin-3490 scope=dapr.runtime type=log ver=1.0.1
time="2021-04-20T11:11:14.0044456+08:00" level=info msg="actor runtime started. actor idle timeout: 1h0m0s. actor scan interval: 30s" app_id=demo_actor instance=tanxin-3490 scope=dapr.runtime.actor type=log ver=1.0.1
time="2021-04-20T11:11:14.0134723+08:00" level=info msg="dapr initialized. Status: Running. Init Elapsed 3444.747ms" app_id=demo_actor instance=tanxin-3490 scope=dapr.runtime type=log ver=1.0.1

//2------------------------------
Those are total logs and no more logs to output.  Compared to logs of examples\Actor\DemoActor, I found that my service seemed stoped somewhere without finishing the setup of actor runtime.

//3--------------------------------
Here are correct logs from DemoActor
.....
You're up and running! Both Dapr and your app logs will appear here.

== APP == info: Microsoft.Hosting.Lifetime[0]

== APP ==       Now listening on: http://localhost:5000

== APP == info: Microsoft.Hosting.Lifetime[0]

== APP ==       Application started. Press Ctrl+C to shut down.

== APP == info: Microsoft.Hosting.Lifetime[0]

== APP ==       Hosting environment: Development

== APP == info: Microsoft.Hosting.Lifetime[0]

== APP ==       Content root path: E:\work\dapr\start\actors\dotnet-sdk\examples\Actor\DemoActor

time="2021-04-20T10:27:02.4803583+08:00" level=info msg="application discovered on port 5000" app_id=demo_actor instance=tanxin-3490 scope=dapr.runtime type=log ver=1.0.1
== APP == info: Microsoft.AspNetCore.Hosting.Diagnostics[1]

== APP ==       **Request starting HTTP/1.1 GET http://127.0.0.1:5000/dapr/config application/json**

== APP == info: Microsoft.AspNetCore.Routing.EndpointMiddleware[0]

== APP ==       Executing endpoint '**Dapr Actors Config**'

== APP == info: Microsoft.AspNetCore.Routing.EndpointMiddleware[1]

== APP ==       Executed endpoint 'Dapr Actors Config'

== APP == info: Microsoft.AspNetCore.Hosting.Diagnostics[2]

== APP ==       Request finished in 51.9725ms 200 application/json

//4---------------------------------------------------------------------------------
When I run a client I got the the error:
Dapr.Actors.ActorMethodInvocationException
  HResult=0x80131500
  Message=Remote Actor Method Exception
  Source=Dapr.Actors
  StackTrace:
   at Dapr.Actors.DaprHttpInteractor.<InvokeActorMethodWithRemotingAsync>d__10.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
  ......

Inner Exception 1:
ActorInvokeException: Object reference not set to an instance of an object.
 
//5-------------------------------------------------------------------------------------------
Could someone help me out! Thanks a lot!

**Comment by mjtansin** [comment]
Sorry, dapr setup corrlectly, the error  was a bug about dependence injection.
