### ISSUE TITLE
Dapr Resource Bindings HTTP GET from external service

### ISSUE THREAD

**Issue by latala43** [dapr/dotnet-sdk#732]
I tried to create a Dapr component like the following:

```
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: nominatim
  namespace: default
spec:
  type: bindings.http
  version: v1
  metadata:
  - name: url
    value: https://nominatim.openstreetmap.org
  - name: method
    value: GET
  - name: UserAgent
    value: Other
```

Then in my service I Invoked this binging like this:

```
 var getAddressUrl = $"{UriString}/reverse?format=jsonv2&lat={latitude}&lon={longitude}&zoom=18&addressdetails=1";

var invokeBindingAsync = _daprClient.InvokeBindingAsync<object, AddressLocationDto>(
    DaprComponentsSettings.HttpNominatim,
    DaprComponentsSettings.CreateBindingOperation,
    null,
    new Dictionary<string, string>
    {
        ["url"] = getAddressUrl
    });
var address = await invokeBindingAsync;
return address;
```

Unfortunately, I receive the following error:
```
Status(StatusCode="Internal", Detail="Error starting gRPC call. HttpRequestException: Connection refused (127.0.0.1:50001) SocketException: Connection refused", DebugException="System.Net.Http.HttpRequestException: Connection refused (127.0.0.1:50001)
 ---> System.Net.Sockets.SocketException (111): Connection refused
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
   at System.Net.Sockets.Socket.<ConnectAsync>g__WaitForConnectWithCancellation|283_0(AwaitableSocketAsyncEventArgs saea, ValueTask connectTask, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.DefaultConnectAsync(SocketsHttpConnectionContext context, CancellationToken cancellationToken)
   at System.Net.Http.ConnectHelper.ConnectAsync(Func`3 callback, DnsEndPoint endPoint, HttpRequestMessage requestMessage, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.ConnectHelper.ConnectAsync(Func`3 callback, DnsEndPoint endPoint, HttpRequestMessage requestMessage, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttp2ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at Grpc.Net.Client.Internal.GrpcCall`2.RunCall(HttpRequestMessage request, Nullable`1 timeout)")
``` 

I do not know how to call HTTP get like this. Please help.

**Comment by latala43** [comment]
There was a typo in the configuration.
