### ISSUE TITLE
system.InvalidCastException: Unable to cast object of type 'Microsoft.AspNetCore.Routing.Patterns.RoutePatternParameterPart' to type 'Microsoft.AspNetCore.Routing.Patterns.RoutePatternLiteralPart'.

### ISSUE THREAD

**Issue by saber-wang** [dapr/dotnet-sdk#791]
Error reporting using apiversion

```csharp
    [ApiVersion("1.0")]
    [Route("api/v{version:apiVersion}/[controller]")]
    [ApiController]
    public class SubscriptionEventsController : SaaSControllerBase
    {
        private readonly ILogger _logger;

        public SubscriptionEventsController(ILogger<ServiceInvocationController> logger)
        {
            _logger = logger;
        }

        
        [Topic(DaprDefaults.BusDefaults.DAPR_PUBSUB_NAME, nameof(DaprDemo_TestEvent))]
        [HttpPost("subscription")]
        public void Subscription(DaprDemo_TestEvent demoEvent)
        {
            _logger.LogInformation("Subscription===>{@demoEvent}", demoEvent);
        }

    }
```
access /dapr/subscrib

error:
```
An unhandled exception has occurred while executing the request.
System.InvalidCastException: Unable to cast object of type 'Microsoft.AspNetCore.Routing.Patterns.RoutePatternParameterPart' to type 'Microsoft.AspNetCore.Routing.Patterns.RoutePatternLiteralPart'.
   at System.Linq.Enumerable.CastIterator[TResult](IEnumerable source)+MoveNext()
   at System.Linq.Enumerable.SelectEnumerableIterator`2.MoveNext()
   at System.String.Concat(IEnumerable`1 values)
   at Microsoft.AspNetCore.Builder.DaprEndpointRouteBuilderExtensions.<>c.<RoutePatternToString>b__3_0(RoutePatternPathSegment segment)
   at System.Linq.Enumerable.SelectArrayIterator`2.MoveNext()
   at System.String.Join(String separator, IEnumerable`1 values)
   at Microsoft.AspNetCore.Builder.DaprEndpointRouteBuilderExtensions.RoutePatternToString(RoutePattern routePattern)
   at Microsoft.AspNetCore.Builder.DaprEndpointRouteBuilderExtensions.<>c.<CreateSubscribeEndPoint>b__2_11(ValueTuple`6 e)
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.ToList()
   at Microsoft.AspNetCore.Builder.DaprEndpointRouteBuilderExtensions.<>c__DisplayClass2_0.<CreateSubscribeEndPoint>b__5(IOrderedEnumerable`1 e)
   at System.Linq.Utilities.<>c__DisplayClass2_0`3.<CombineSelectors>b__0(TSource x)
   at System.Linq.Enumerable.SelectEnumerableIterator`2.ToArray()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.OrderedEnumerable`1.GetEnumerator()+MoveNext()
   at System.Text.Json.Serialization.Converters.IEnumerableOfTConverter`2.OnWriteResume(Utf8JsonWriter writer, TCollection value, JsonSerializerOptions options, WriteStack& state)
   at System.Text.Json.Serialization.Converters.IEnumerableDefaultConverter`2.OnTryWrite(Utf8JsonWriter writer, TCollection value, JsonSerializerOptions options, WriteStack& state)
   at System.Text.Json.Serialization.JsonConverter`1.TryWrite(Utf8JsonWriter writer, T& value, JsonSerializerOptions options, WriteStack& state)
   at System.Text.Json.Serialization.JsonConverter`1.WriteCore(Utf8JsonWriter writer, T& value, JsonSerializerOptions options, WriteStack& state)
   at System.Text.Json.JsonSerializer.WriteCore[TValue](JsonConverter jsonConverter, Utf8JsonWriter writer, TValue& value, JsonSerializerOptions options, WriteStack& state)
   at System.Text.Json.JsonSerializer.WriteCore[TValue](Utf8JsonWriter writer, TValue& value, Type inputType, JsonSerializerOptions options)
   at System.Text.Json.JsonSerializer.Serialize[TValue](TValue& value, Type inputType, JsonSerializerOptions options)
   at System.Text.Json.JsonSerializer.Serialize[TValue](TValue value, JsonSerializerOptions options)
   at Microsoft.AspNetCore.Builder.DaprEndpointRouteBuilderExtensions.<>c.<<CreateSubscribeEndPoint>b__2_0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
```

**Comment by fbridger** [comment]
Removing or hardcoding the `version` from the controller route fixes the issue? 
```
[Route("api/v1.0/[controller]")]
```

**Comment by saber-wang** [comment]
@fbridger  Yes, it can be solved. Apiversion cannot be supported

**Comment by halspang** [comment]
@saber-wang - Given the fix, does this work for you? Or do you think we should have the direct support for `ApiVersion`?

**Comment by saber-wang** [comment]
@halspang  If you can support, this is the best. If you can't, I'll use hard coding😉

**Comment by saber-wang** [comment]
@itsoli91 Because dapr does not support subscribing to the same topic multiple times in an instance, it is meaningless to support versions.
@halspang For this error, I think we should throw more explicit exceptions and add relevant documents.

**Comment by vimateck** [comment]
Hello,

we have also encountered this problem. We would like to have the ability to define multiple api versions within a controller and also map them to the pub sub model of dapr.

As far as I understand the ASP.net implementation, I can do the following:
```csharp
[ApiController]
[ApiVersion("1.0")]
[ApiVersion("2.0")]
[route("api/v{v:apiVersion}/test")]
public class TestController : ControllerBase
{
    [Topic(DaprComponents.PubSub, "pubsub-test")]
    [HttpPost("pubsub")]
    [MapToApiVersion("1.0")]
    public IActionResult PubSubTest()
    {
        return Ok("PubSubTest");
    }

    [Topic(DaprComponents.PubSub, "pubsub-test")]
    [HttpPost("pubsub2")]
    [MapToApiVersion("2.0")]
    public IActionResult PubSubTest2()
    {
        return Ok("PubSubTest2");
    }
}
```

I have defined two versions within the controller and mapped the two actions to a specific version each.

I would now expect the Dapr Topic subscription to use the version defined using `MapToApiVersion` (or, if only one `ApiVersion` is defined, use the only existing one).

Right now, [DaprEndpointRouteBuilderExtensions:201](https://github.com/dapr/dotnet-sdk/blob/master/src/Dapr.AspNetCore/DaprEndpointRouteBuilderExtensions.cs#L201) is trying to turn the path segment into a `RoutePatternLiteralPart`, but if we are working with variables within the path, it could also be a `RoutePatternParameterPart`.

Is there a plan to support these parameters in the near future?

**Comment by WhitWaldo** [comment]
> Hi this is an issue for us, we have just upgraded to .NET 10 and even with the rc build of the SDK its still occuring. we are using the Topic attributes and the /dapr/subscribe endpoint generated by dapr is causing this exception.
> 
> We are using versioning in our API but haven't specifically excluded or included the dapr subscribe endpoint in the versioning. You really need to handle versioning, any API that doesn't include versioning is not designing their API properly so can we get a resolution to this please.

As I confirmed in #1657, after discussions with the runtime maintainers, the runtime only supports one endpoint per topic per subscription. While the SDK might theoretically try to juggle multiple routes to accommodate your API versioning pattern, that wouldn't be trivial. All endpoints must be declared up-front, and routing cannot be deferred to the runtime nor inferred dynamically - those simply aren't supported runtime capabilities and adding it to the SDK alone doesn't change that limitation.

This limitation is precisely why [streaming subscriptions](https://docs.dapr.io/developing-applications/sdks/dotnet/dotnet-messaging/dotnet-messaging-pubsub-howto/#set-up-message-handler) exist - to allow message handling logic to branch at runtime without needing layers of static routing workarounds.

This issue predates my time as maintainer by quite a while, and your comment is the first time it's been raised with me. This strongly suggests this isn't a common pain point for the broader user base, despite how critical it might be for your particular setup.

As with any longstanding open issue in an open-source project, the absence of a PR generally means no one has considered it important enough to invest the necessary engineering effort towards. If this is mission-critical in your environment, you're more than welcome to be the person that finally moves it forward. 

Any PR that respects the runtime constraints, avoids breaking SDK behavior, and is technically sound will absolutely be reviewed as a merge candidate.

To be candid, this isn't something I plan to prioritize. The streaming subscription path already provides a clean and supported solution, and there hasn't been meaningful interest in this feature for years.
