### ISSUE TITLE
Dapr Actor system exception after stopping at a breakpoint while debugging

### ISSUE THREAD

**Issue by francotiveron** [dapr/dotnet-sdk#875]
## Expected Behavior
If breapoint is hit in actor code, and after some debugging (few minutes) the execution is restored (F5), no actor error should occur

## Actual Behavior
more often than not a transient exception is raised

```
Dapr.DaprApiException: error invoke actor method: error finding address for actor type MineActor with id ESM2_Index
   at Dapr.Actors.DaprHttpInteractor.SendAsyncHandleUnsuccessfulResponse(Func`1 requestFunc, String relativeUri, CancellationToken cancellationToken)
   at Dapr.Actors.DaprHttpInteractor.SendAsync(Func`1 requestFunc, String relativeUri, CancellationToken cancellationToken)
   at Dapr.Actors.DaprHttpInteractor.InvokeActorMethodWithRemotingAsync(ActorMessageSerializersManager serializersManager, IActorRequestMessage remotingRequestRequestMessage, CancellationToken cancellationToken)
   at Dapr.Actors.Communication.Client.ActorRemotingClient.InvokeAsync(IActorRequestMessage remotingRequestMessage, CancellationToken cancellationToken)
   at Dapr.Actors.Client.ActorProxy.InvokeMethodAsync(Int32 interfaceId, Int32 methodId, String methodName, IActorRequestMessageBody requestMsgBodyValue, CancellationToken cancellationToken)
```

After 2/3s the exceptions stops.

## Steps to Reproduce the Problem
- Run an app with an actor in standalone mode, either with VS or VS Code. the application code should be some kind of loop that continuously calls a method in the actor in a try catch block that logs the exception
- Put a breakpoint in the called actor method
- Wait in the breakpoint for some time, perhaps stepping few times through the code.
- Remove the breakpoint and resume execution

N.B. it doesn't occur all the times

**Comment by francotiveron** [comment]
@halspang
I understand. The important thing is that this has an explanation and doesn't show a buried bug that could manifest in production. I'll close this issue.

However, at a second level, perhaps it is possible to do something to detect whether the app is under debugger and suspend the health checks and timeouts. One option is some env. variable.
