### ISSUE TITLE
Actor method invocation throws error for Services in different solution

### ISSUE THREAD

**Issue by msislam3** [dapr/dotnet-sdk#894]
I have two services Service1 and Service2. Service1 supports Actor1 which has method1.

Service2 would invoke Actor1.method1 in Service1
 
Now when both Services are in same solution with the common interface and classes in a Common project referenced by both the services the call from Service2 to Actor1.method1 is successful

But if the Services are in different solution where the common interface and classes are just copied in both solution (with same namespace) the call fails with exception

```
fail: facade.Controllers.AlarmController[0]
== APP ==       [null]
== APP ==       Dapr.Actors.ActorMethodInvocationException: Remote Actor Method Exception
== APP ==        ---> Dapr.Actors.ActorInvokeException: Element 'urn:actors:value' contains data of the 'urn:actors:UpdateAttributesAsyncReqBody' data contract. The deserializer has no knowledge of any type that maps to this contract. Add the type corresponding to 'UpdateAttributesAsyncReqBody' to the list of known types - for example, by using the KnownTypeAttribute attribute or by adding it to the list of known types passed to DataContractSerializer.
== APP ==          --- End of inner exception stack trace ---
== APP ==          at Dapr.Actors.DaprHttpInteractor.InvokeActorMethodWithRemotingAsync(ActorMessageSerializersManager serializersManager, IActorRequestMessage remotingRequestRequestMessage, CancellationToken cancellationToken)
== APP ==          at Dapr.Actors.Communication.Client.ActorRemotingClient.InvokeAsync(IActorRequestMessage remotingRequestMessage, CancellationToken cancellationToken)
== APP ==          at Dapr.Actors.Client.ActorProxy.InvokeMethodAsync(Int32 interfaceId, Int32 methodId, String methodName, IActorRequestMessageBody requestMsgBodyValue, CancellationToken cancellationToken)
== APP ==          at facade.Controllers.AlarmController.<WellSubscription>b__4_0() in E:\Project\alarm-manager\facade\Controllers\AlarmController.cs:line 66
== APP == info: facade.Controllers.AlarmController[0]
```

I was wondering why the two cases are different given all the common actor interface and classes have similar structure and namespace in the second scenario

**Comment by halspang** [comment]
@msislam3 - Thanks for opening this issue!

I've never seen this error before, if I had to guess it has to do with how .NET is handling the serialization. If the two projects don't have knowledge of each other, did you recreate the data class in both solutions? I'm not super familiar with how remoting's serialization works, but I would bet it needs to have knowledge of the class to handle that. 

Is there a reason you want to have both of these projects fully isolated instead of sharing the common model? 

Regardless, I'll see if I can find some time to reproduce this.

**Comment by msislam3** [comment]
Yes, both the solution have the exact same project (same project name, assembly name, namespace) with all the data classes replicated.

The setup is like this because the two services are in two different repo. I don't think we would be able to bring the two services in the same repo to share a common project. The other possibility is to create a nuget package from one repo and use it in another but I am  not sure if that would work. It would be better for now if I can make it work with the current setup

**Comment by halspang** [comment]
@msislam3 - Making a Nuget package should work. Or putting the common code in a 3rd repo that they can both depend on. This is a better coding practice as well as you'd only have to update the interface in one place and then both solutions could know about it.
