### ISSUE TITLE
bindings.azure.blobstorage:Exception of type 'System.OutOfMemoryException' was thrown.

### ISSUE THREAD

**Issue by kou-h** [dapr/dotnet-sdk#903]
Hello, I'm using bindings azure. Blobstorage for file upload. The uploaded file is relatively large, about 10MB. The first upload was successful, but the following error occurred in the second upload of files above 10MB. There is no problem uploading small files (about 200K). What can I do to solve this problem. thank you

Package Dapr.AspNetCore Version="1.7.0"

ERROR    at System.GC.AllocateNewArray(IntPtr typeHandle, Int32 length, GC_ALLOC_FLAGS flags)
at System.GC.<AllocateUninitializedArray>g__AllocateNewUninitializedArray|66_0[T](Int32 length, Boolean pinned)
at System.Buffers.TlsOverPerCoreLockedStacksArrayPool`1.Rent(Int32 minimumLength)
at System.Text.Json.Utf8JsonWriter.WriteStringEscapeValue(ReadOnlySpan`1 value, Int32 firstEscapeIndexVal)
at System.Text.Json.Utf8JsonWriter.WriteStringValue(ReadOnlySpan`1 value)
at System.Text.Json.Serialization.Converters.StringConverter.Write(Utf8JsonWriter writer, String value, JsonSerializerOptions options)
at System.Text.Json.Serialization.JsonConverter`1.TryWrite(Utf8JsonWriter writer, T& value, JsonSerializerOptions options, WriteStack& state)
at System.Text.Json.Serialization.JsonConverter`1.WriteCore(Utf8JsonWriter writer, T& value, JsonSerializerOptions options, WriteStack& state)
at System.Text.Json.JsonSerializer.WriteUsingSerializer[TValue](Utf8JsonWriter writer, TValue& value, JsonTypeInfo jsonTypeInfo)
at System.Text.Json.JsonSerializer.WriteBytesUsingSerializer[TValue](TValue& value, JsonTypeInfo jsonTypeInfo)
at System.Text.Json.JsonSerializer.SerializeToUtf8Bytes[TValue](TValue value, JsonSerializerOptions options)
at Dapr.Client.TypeConverters.ToJsonByteString[T](T data, JsonSerializerOptions options)
at Dapr.Client.DaprClientGrpc.InvokeBindingAsync[TRequest](String bindingName, String operation, TRequest data, IReadOnlyDictionary`2 metadata, CancellationToken cancellationToken)

Exception of type 'System.OutOfMemoryException' was thrown.

**Comment by halspang** [comment]
@kou-h - Thanks for opening this issue! What environment are you running your app in? Does this happen on the 2nd request? Or is it just sometime after the first?

**Comment by kou-h** [comment]
@halspang 
Hello,The app running environment is azure k8s. There is no problem uploading large files for the first time. This error occurs when uploading large files for the second time, and then small files will not appear this error. thank you

**Comment by kou-h** [comment]
@halspang 
Hello, this problem is solved. Increased the memory of the container. But now when downloading large files, the following problems occur. How can I solve it.
Status(StatusCode="ResourceExhausted", Detail="Received message exceeds the maximum configured message size.")

**Comment by halspang** [comment]
@kou-h - Glad you got past the first issue. For the 2nd one, is that a log from Dapr or from your app? I know there are some limits in terms of request size but we should track down if it's the binding or the SDK first.

**Comment by kou-h** [comment]
@halspang 
  Thanks for your reply. I added the following code to solve this problem. Is this setting ok? thank you

  builder.Services.AddControllers().AddDapr(x => x.UseGrpcChannelOptions(new Grpc.Net.Client.GrpcChannelOptions()
        {
            MaxReceiveMessageSize = 150 * 1024 * 1024,
        }));

**Comment by halspang** [comment]
That looks like the correct way to do it to me! Glad you could get it working. Do you need anything else, or can we close the issue?

**Comment by kou-h** [comment]
@halspang 
Thank you very much.This issue can be closed, thanks again
