### ISSUE TITLE
How to run c# actor example?

### ISSUE THREAD

**Issue by rquackenbush** [dapr/dotnet-sdk#910]
I followed the instructions here: https://docs.dapr.io/developing-applications/sdks/dotnet/dotnet-actors/dotnet-actors-howto/

I am able to launch the service app with:
```
PS C:\codepersonal\DaprActor\MyActorService> dapr run --app-id myapp --app-port 5000 --dapr-http-port 3500 -- dotnet run
Starting Dapr with id myapp. HTTP Port: 3500. gRPC Port: 62594
time="2022-07-20T09:10:05.9495618-04:00" level=info msg="starting Dapr Runtime -- version 1.8.0 -- commit dc7f86840c85a1eff2e1223456994f554ea31d11" app_id=myapp instance=LAP-J699LN3 scope=dapr.runtime type=log ver=1.8.0
time="2022-07-20T09:10:05.9495618-04:00" level=info msg="log level set to: info" app_id=myapp instance=LAP-J699LN3 scope=dapr.runtime type=log ver=1.8.0
time="2022-07-20T09:10:05.9495618-04:00" level=info msg="metrics server started on :62595/" app_id=myapp instance=LAP-J699LN3 scope=dapr.metrics type=log ver=1.8.0
time="2022-07-20T09:10:05.952561-04:00" level=info msg="standalone mode configured" app_id=myapp instance=LAP-J699LN3 scope=dapr.runtime type=log ver=1.8.0
time="2022-07-20T09:10:05.952561-04:00" level=info msg="app id: myapp" app_id=myapp instance=LAP-J699LN3 scope=dapr.runtime type=log ver=1.8.0
time="2022-07-20T09:10:05.952561-04:00" level=info msg="mTLS is disabled. Skipping certificate request and tls validation" app_id=myapp instance=LAP-J699LN3 scope=dapr.runtime type=log ver=1.8.0
time="2022-07-20T09:10:05.960562-04:00" level=info msg="local service entry announced: myapp -> 192.168.1.215:62599" app_id=myapp instance=LAP-J699LN3 scope=dapr.contrib type=log ver=1.8.0
time="2022-07-20T09:10:05.960562-04:00" level=info msg="Initialized name resolution to mdns" app_id=myapp instance=LAP-J699LN3 scope=dapr.runtime type=log ver=1.8.0
time="2022-07-20T09:10:05.960562-04:00" level=info msg="loading components" app_id=myapp instance=LAP-J699LN3 scope=dapr.runtime type=log ver=1.8.0
time="2022-07-20T09:10:05.9635631-04:00" level=info msg="component loaded. name: pubsub, type: pubsub.redis/v1" app_id=myapp instance=LAP-J699LN3 scope=dapr.runtime type=log ver=1.8.0
time="2022-07-20T09:10:05.9635631-04:00" level=info msg="waiting for all outstanding components to be processed" app_id=myapp instance=LAP-J699LN3 scope=dapr.runtime type=log ver=1.8.0
time="2022-07-20T09:10:05.9655637-04:00" level=info msg="detected actor state store: statestore" app_id=myapp instance=LAP-J699LN3 scope=dapr.runtime type=log ver=1.8.0
time="2022-07-20T09:10:05.9655637-04:00" level=info msg="component loaded. name: statestore, type: state.redis/v1" app_id=myapp instance=LAP-J699LN3 scope=dapr.runtime type=log ver=1.8.0
time="2022-07-20T09:10:05.9655637-04:00" level=info msg="all outstanding components processed" app_id=myapp instance=LAP-J699LN3 scope=dapr.runtime type=log ver=1.8.0
time="2022-07-20T09:10:05.9655637-04:00" level=info msg="gRPC proxy enabled" app_id=myapp instance=LAP-J699LN3 scope=dapr.runtime type=log ver=1.8.0
time="2022-07-20T09:10:05.9665635-04:00" level=info msg="enabled gRPC tracing middleware" app_id=myapp instance=LAP-J699LN3 scope=dapr.runtime.grpc.api type=log ver=1.8.0
time="2022-07-20T09:10:05.9665635-04:00" level=info msg="enabled gRPC metrics middleware" app_id=myapp instance=LAP-J699LN3 scope=dapr.runtime.grpc.api type=log ver=1.8.0
time="2022-07-20T09:10:05.9665635-04:00" level=info msg="API gRPC server is running on port 62594" app_id=myapp instance=LAP-J699LN3 scope=dapr.runtime type=log ver=1.8.0
time="2022-07-20T09:10:05.9665635-04:00" level=info msg="enabled metrics http middleware" app_id=myapp instance=LAP-J699LN3 scope=dapr.runtime.http type=log ver=1.8.0
time="2022-07-20T09:10:05.9665635-04:00" level=info msg="enabled tracing http middleware" app_id=myapp instance=LAP-J699LN3 scope=dapr.runtime.http type=log ver=1.8.0
time="2022-07-20T09:10:05.9665635-04:00" level=info msg="http server is running on port 3500" app_id=myapp instance=LAP-J699LN3 scope=dapr.runtime type=log ver=1.8.0
time="2022-07-20T09:10:05.9665635-04:00" level=info msg="The request body size parameter is: 4" app_id=myapp instance=LAP-J699LN3 scope=dapr.runtime type=log ver=1.8.0
time="2022-07-20T09:10:05.9665635-04:00" level=info msg="enabled gRPC tracing middleware" app_id=myapp instance=LAP-J699LN3 scope=dapr.runtime.grpc.internal type=log ver=1.8.0
time="2022-07-20T09:10:05.9665635-04:00" level=info msg="enabled gRPC metrics middleware" app_id=myapp instance=LAP-J699LN3 scope=dapr.runtime.grpc.internal type=log ver=1.8.0
time="2022-07-20T09:10:05.9665635-04:00" level=info msg="internal gRPC server is running on port 62599" app_id=myapp instance=LAP-J699LN3 scope=dapr.runtime type=log ver=1.8.0
time="2022-07-20T09:10:05.9665635-04:00" level=info msg="application protocol: http. waiting on port 5000.  This will block until the app is listening on that port." app_id=myapp instance=LAP-J699LN3 scope=dapr.runtime type=log ver=1.8.0
== APP == Building...
Updating metadata for app command: dotnet run
You're up and running! Both Dapr and your app logs will appear here.

== APP == info: Microsoft.Hosting.Lifetime[14]
== APP ==       Now listening on: https://localhost:7257
== APP == info: Microsoft.Hosting.Lifetime[14]
== APP ==       Now listening on: http://localhost:5037
== APP == info: Microsoft.Hosting.Lifetime[0]
== APP ==       Application started. Press Ctrl+C to shut down.
== APP == info: Microsoft.Hosting.Lifetime[0]
== APP ==       Hosting environment: Development
== APP == info: Microsoft.Hosting.Lifetime[0]
== APP ==       Content root path: C:\codepersonal\DaprActor\MyActorService\
```

And when I launch the client:
```
PS C:\codepersonal\DaprActor\MyActorClient> dotnet run
Startup up...
Calling SetDataAsync on MyActor:1...
Unhandled exception. Dapr.DaprApiException: the state store is not configured to use the actor runtime. Have you set the - name: actorStateStore value: "true" in your state store component file?
   at Dapr.Actors.DaprHttpInteractor.SendAsyncHandleUnsuccessfulResponse(Func`1 requestFunc, String relativeUri, CancellationToken cancellationToken)
   at Dapr.Actors.DaprHttpInteractor.SendAsync(Func`1 requestFunc, String relativeUri, CancellationToken cancellationToken)
   at Dapr.Actors.DaprHttpInteractor.InvokeActorMethodWithRemotingAsync(ActorMessageSerializersManager serializersManager, IActorRequestMessage remotingRequestRequestMessage, CancellationToken cancellationToken)
   at Dapr.Actors.Communication.Client.ActorRemotingClient.InvokeAsync(IActorRequestMessage remotingRequestMessage, CancellationToken cancellationToken)
   at Dapr.Actors.Client.ActorProxy.InvokeMethodAsync(Int32 interfaceId, Int32 methodId, String methodName, IActorRequestMessageBody requestMsgBodyValue, CancellationToken cancellationToken)
   at Dapr.Actors.Client.ActorProxy.ContinueWithResult[TRetval](Int32 interfaceId, Int32 methodId, Task`1 task)
   at Program.<Main>$(String[] args) in C:\codepersonal\DaprActor\MyActorClient\Program.cs:line 23
   at Program.<Main>(String[] args)
```

statestore.yaml:
```yaml
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: statestore
spec:
  type: state.redis
  version: v1
  metadata:
  - name: redisHost
    value: localhost:6379
  - name: redisPassword
    value: ""
  - name: actorStateStore
    value: "true"

```

Environment:
- Windows 10
- .NET SDK 6.0.302
-  Docker for Desktop 4.10.1

How do I get past that exception?

**Comment by halspang** [comment]
The app port and what the app is actually listening on is important here. You specified `--app-port 5000` when the example uses `--app-port 5010`. I also noticed that your actual application appears to be listening on `5037`.

When that happens, the runtime doesn't finish initializing because it is waiting for your app to respond on a port that it isn't listening to. Update the port and you should be good to go. I did run through the example myself just to make sure everything was good here.

**Comment by rquackenbush** [comment]
Ahh - the fundamental issue was I have .NET 6 installed, and it has a new way of configurating ASP.NET core. I recreated using .NET 5 and everything worked according to the docs.  Thanks for your help!
