### ISSUE TITLE
Unable to fetch secret as daprClient.GetSecretAsync returning error

### ISSUE THREAD

**Issue by nelson-b** [dapr/dotnet-sdk#952]
## Expected Behavior

Should fetch the secret from azure key vault using c sharp dapr client

## Actual Behavior

When executing 

daprClient.GetSecretAsync getting below error

Dapr.DaprException
  HResult=0x80131500
  Message=Secret operation failed: the Dapr endpoint indicated a failure. See InnerException for details.
  Source=<Cannot evaluate the exception source>
  StackTrace:
<Cannot evaluate the exception stack trace>

  This exception was originally thrown at this call stack:
    [External Code]

Inner Exception 1:
RpcException: Status(StatusCode="Internal", Detail="Error starting gRPC call. HttpRequestException: An HTTP/2 connection could not be established because the server did not complete the HTTP/2 handshake.", DebugException="System.Net.Http.HttpRequestException: An HTTP/2 connection could not be established because the server did not complete the HTTP/2 handshake.
   at System.Net.Http.HttpConnectionPool.ReturnHttp2Connection(Http2Connection connection, Boolean isNewConnection)
   at System.Net.Http.HttpConnectionPool.AddHttp2ConnectionAsync(HttpRequestMessage request)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.MoveNext(Thread threadPoolThread)
   at System.Runtime.CompilerServices.TaskAwaiter.<>c.<OutputWaitEtwEvents>b__12_0(Action innerContinuation, Task innerTask)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.ContinuationWrapper.Invoke()
   at System.Threading.Tasks.AwaitTaskContinuation.System.Threading.IThreadPoolWorkItem.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
   at System.Threading.Thread.StartCallback()
--- End of stack trace from previous location ---
   at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttp2ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at Grpc.Net.Client.Internal.GrpcCall`2.RunCall(HttpRequestMessage request, Nullable`1 timeout)")

## Steps to Reproduce the Problem

1) Install dapr, configure azure key vault yaml file.
2) run dapr side car engine
3) Verify if you are able to fetch the secret using dapr secret API in postman
4) If yes, then execute below code in c sharp
// Create Dapr Client
var daprClient = new DaprClientBuilder()
               .UseHttpEndpoint("http://127.0.0.1:50001/v1.0/secrets/")
               .UseJsonSerializationOptions(default)
               .Build();

// Add the DaprClient to DI.

builder.Services.AddSingleton<DaprClient>(daprClient);
var noProxy = Environment.GetEnvironmentVariable("no_proxy");

//Using Dapr SDK to invoke a method

var secret = await daprClient.GetSecretAsync("azuresecretstore", "appcs-id-Primary"); <= Getting error
Console.WriteLine($"Result: {string.Join(", ", secret)}");

**Comment by halspang** [comment]
@nelson-b - What ports is your dapr sidecar running on? It looks like the connection was refused talking to it.

**Comment by halspang** [comment]
@nelson-b - I've confirmed that I have no problem fetching a secret from Azure Keyvault with the client. Can you give some more information on how you're connecting/running Dapr?

**Comment by flomader** [comment]
I am having the same issue accessing a statestore (SQL Server). It only occurs when I start Dapr via CLI:
`dapr run --app-id MyApp --components-path .\components`
If I run daprd it works:
`daprd --app-id MyApp --components-path .\components`

If I use the CLI and start my application together with dapr in the same command line call then it works as well:
`dapr run --app-id MyApp --components-path .\components dotnet run`
I am on Windows.

**Comment by jlemmons** [comment]
I am getting this same error.

My experience is exactly like @flomader . Statestore, SQL Server, Windows and I'm getting the same results from those commands.

**Comment by william-liebenberg** [comment]
Im also suffering from this at the moment just trying to access redis state store from my .NET 7 apps :(

Tried multiple runtimes (v1.10 and v1.9.5) and both are behaving exactly the same way. Made sure I was also running in admin mode too.

I also tried both running my apps with `http` and `https` (by adding `--app-ssl`)

I tried using `daprd` directly as @flomader suggested but the results are the same.

Im on Windows 11.

My apps run successfully if i run them with `dapr run <all the configs> -- dotnet run` but this makes debugging the apps a bit harder because i have to manually attach the debugger...

This is severely hurting my local dev experience :( 

Any advice?

**Comment by jlemmons** [comment]
We were able to get around this by using Dapr Sidekick https://github.com/man-group/dapr-sidekick-dotnet

It only required adding the Man.Dapr.Sidekick.AspNetCore nuget package and adding this line to Program.cs

builder.Services.AddDaprSidekick(builder.Configuration, p => 
        p.Sidecar = new DaprSidecarOptions() { AppId = "MyApp", ComponentsDirectory = "./components" });
